using System.Collections.Generic;
namespace RTMaquetaXR { internal static partial class ModLocalization {
    static partial void AddGuide64(Dictionary<string,string> entries) {
        Add(entries,"The centre identifies the active weapon or equipment set with its original art. Changing weapon is distinct from attacks, ammunition/effects and reload. Switch weapon appears only when at least two loadouts contain equipped weapons; empty slots are not alternatives. The wheel follows the selected actor, current equipment and available abilities. After a weapon change the wheel refreshes: centre the stick and release confirmation before choosing the next action.","El centro identifica el arma o conjunto activo con su arte original. Cambiar arma se distingue de ataques, munición/efectos y recarga. Cambiar arma sólo aparece si al menos dos conjuntos contienen armas equipadas; las casillas vacías no son alternativas. La rueda sigue al personaje seleccionado, su equipo y sus habilidades actuales. Tras cambiar de arma se actualiza: centra el stick y suelta la confirmación antes de elegir otra acción.");
        Add(entries,"A short RIGHT stick click shows/hides contextual controls in On-foot exploration, Ground combat and Space combat. Holding it for 1 s in exploration frames the group without toggling help. Release and centre the RIGHT stick before moving again. Hold button Y in exploration to highlight objects. Hints stay hidden on the main menu, maps and dialogue. Adjust placement and size in Advanced settings. The separate gesture indicator is optional and off by default.","Un clic corto del stick DERECHO muestra u oculta controles en Exploración a pie, Combates terrestres y Combate espacial. Mantenerlo 1 s en exploración encuadra el grupo sin alternar la ayuda. Suelta y centra el stick DERECHO antes de volver a moverte. Mantén Y en exploración para resaltar objetos. Las ayudas no aparecen en el menú principal, mapas ni diálogos. Ajusta su posición y tamaño en Configuración avanzada. El indicador de gestos es opcional y está desactivado por defecto.");
        Add(entries,"Choose rendering, output resolution, DLSS scale and engine effects on the main page. Select Virtual Desktop (VDXR) or Meta Quest Link / Air Link through OpenXR runtime; a runtime change requires restarting the game. Controls are shared by both. Custom starts with the reference configuration; SAVE stores your complete current setup and confirms it. Reset asks first and discards personal changes. DLSS/DLAA failure displays the current image without AA; TAA remains a separate manual choice.","Elige renderizado, resolución de salida, escala DLSS y efectos del motor en la página principal. Selecciona Virtual Desktop (VDXR) o Meta Quest Link / Air Link en Runtime OpenXR; cambiar de runtime requiere reiniciar el juego. Ambos comparten los controles. Personalizado parte de la configuración de referencia; GUARDAR conserva todos tus ajustes y lo confirma. Restablecer pide confirmación y elimina los cambios personales. Si DLSS/DLAA falla, muestra la imagen sin antialiasing; TAA sigue siendo una elección manual independiente.");
        Add(entries,"LEFT stick / RIGHT pointer + hold RIGHT grip · inspect actor","Stick IZQUIERDO / puntero DERECHO + mantener grip DERECHO · consultar");
        Add(entries,"Hold right grip · card","Mantén grip derecho · ficha");
        Add(entries,"Keep RIGHT grip held · keep information","Mantén grip DERECHO · conservar información");
        Add(entries,"Hold · keep card","Mantener · conservar ficha");
        Add(entries,"Point at ability + hold RIGHT grip · original information","Apunta a habilidad + mantén grip DERECHO · información original");
        Add(entries,"Hold · ability information","Mantener · información");
        Add(entries,"Right stick / left pointer · menu preview","Stick derecho / puntero izquierdo · elegir menú");
        Add(entries,"Choose menu","Elegir menú");
        Add(entries,"LEFT trigger · open pointed menu","Gatillo IZQUIERDO · abrir menú señalado");
        Add(entries,"Open option","Abrir opción");
        Add(entries,"Selective engine cadence is off by default. Its 72/36, 90/45 and 120/60 pairs require restart and do not change headset refresh in either OpenXR runtime. The engine-block switches also apply after restart. They do not halve every game system. Keep a configuration you can compare; your head, Touch and stereo views retain their own update paths.","La cadencia selectiva del motor está desactivada por defecto. Sus pares 72/36, 90/45 y 120/60 requieren reiniciar y no cambian el refresco del visor en ninguno de los runtimes OpenXR. Los interruptores por bloques también se aplican al reiniciar. No reducen a la mitad todos los sistemas del juego. Conserva una configuración que puedas comparar; cabeza, Touch y vistas estéreo mantienen sus propias actualizaciones.");
        Add(entries,"Tutorial: F1 > Help · Touch controls.","Tutorial: F1 > Ayuda · Controles Touch.");
        Add(entries,"1 s · VR settings","1 s · Ajustes VR");
        Add(entries,"Left thumbrest + right stick · draw distance","Apoyo capacitivo izquierdo + stick derecho · distancia de dibujado");
    }
} }
