using System.Collections.Generic;

namespace RTMaquetaXR
{
    internal static partial class ModLocalization
    {
        // English keys are the canonical assignment text. A changed binding
        // invalidates translation coverage until both languages are reviewed.
        static partial void AddGuides(Dictionary<string, string> d)
        {
            Add(d, "Move the selected group in On-foot exploration. Follow moving characters enables smooth travel and quicker direction alignment; off keeps the table still. A held stick keeps its starting heading: centre it to adopt the new heading. HUD hover does not stop movement; clicks and menus do. Space combat uses native pointer orders, never stick piloting. On map panels the stick scrolls native UI or zooms the map when the native camera permits it.", "Mueve el grupo seleccionado al explorar en superficie. Seguir personajes añade desplazamiento suave y alineación más rápida; desactivado mantiene la mesa quieta. Mantener el stick conserva la dirección inicial: céntralo para adoptar otra. Pasar sobre el HUD no detiene el movimiento; los clics y menús sí. En Combate espacial se dan órdenes con el puntero, sin pilotar con el stick. En mapas, el stick desplaza la interfaz o hace zoom si lo permite la cámara nativa.");
            Add(d, "Same table gestures in surface and Space combat.", "Mismos gestos de mesa en superficie y Combate espacial.");
            Add(d, "Hold either grip and move the hand to reposition the tabletop; release to finish. Physical head motion remains free. The same gestures work in Space combat and Dialogue and cutscenes. Space combat starts with a ship-relative frame and does not follow ship turns automatically. Use Advanced settings > Space > Frame active ship for explicit framing. Map and management panels use their own placement settings; grips do not drag them.", "Mantén un grip y mueve la mano para desplazar la maqueta; suelta para terminar. La cabeza se mueve libremente. Funciona igual en Combate espacial y Diálogos y cinemáticas. El Combate espacial comienza con encuadre relativo a la nave y no sigue sus giros automáticamente. Usa Configuración avanzada > Espacio > Encuadrar nave activa para centrarla. Los paneles de mapas y gestión tienen ajustes propios; los grips no los arrastran.");
            Add(d, "On the surface and in Space combat, rotate both servo-skulls or change their separation while holding both grips. Each table has fixed comfort limits; space scale is relative to the ship and does not change your surface zoom setting. Bringing the hands together also leaves surface character head view. Map and management panels use their placement settings instead of these gestures.", "En superficie y en Combate espacial, gira los dos servocráneos o cambia su separación manteniendo ambos grips. Cada mesa tiene límites de comodidad; la escala espacial depende de la nave y no cambia el zoom de superficie. Juntar las manos también sale de la primera persona del personaje. Los paneles de mapas y gestión usan sus ajustes de posición, en lugar de estos gestos.");
            Add(d, "In surface and Space combat, orbit the table at your turn-speed setting, preserving zoom and centre. Dialogue and cutscenes also allow it; head view follows the character instead. In an open wheel its own stick selects abilities or entries; only the surface left wheel switches modes with stick click. The local map has its own zoom/turn controls. Grips, UI presses and selections take priority. Centre the stick after a grip or menu.", "En superficie y en Combate espacial, gira la mesa a tu velocidad configurada, conservando zoom y centro. También funciona en diálogos de superficie; la primera persona sigue al personaje. En una rueda abierta, su stick elige habilidades u opciones; sólo la rueda izquierda terrestre cambia de modo con clic. El mapa local tiene su propio zoom/giro. Grips, clics y selección tienen prioridad. Centra el stick después de un grip o menú.");
            Add(d, "Hold right grip and trigger for 0.15 seconds. On the surface, choose a menu by holding its stick sector for 1 second, or point and click with the LEFT trigger. In Space combat this wheel contains native ship-post abilities: point to preview original information, then A or LEFT trigger activates; no dwell activation. Grey entries cannot execute. Release the opening controls to cancel. All four opening buttons held together reserve VR settings.", "Mantén grip y gatillo derechos durante 0,15 segundos. En superficie, elige un menú manteniendo su sector con el stick 1 segundo, o apunta y pulsa el gatillo IZQUIERDO. En Combate espacial esta rueda contiene habilidades nativas de puestos: señala para ver su ficha y activa con A o gatillo IZQUIERDO, sin activación por permanencia. Las opciones grises no se ejecutan. Suelta la combinación para cancelar. Los cuatro botones juntos reservan la configuración VR.");
            Add(d, "Hold left grip and trigger for 0.15 seconds. Surface modes switch with left stick click: Actions, Party or Combatants. Space combat uses native weapons and actions of the active unit, with no terrestrial mode switch. Point with the stick or RIGHT skull to preview an ability; A or RIGHT trigger activates, without a dwell timer. Party selection uses 1 second or opposite click. Combatant information follows the separate inspection rules. Release grip/trigger to close.", "Mantén grip y gatillo izquierdos durante 0,15 segundos. En superficie, el clic del stick alterna Acciones, Grupo o Combatientes. En Combate espacial aparecen armas y acciones nativas de la unidad activa, sin alternar esos modos terrestres. Señala con stick o cráneo DERECHO para consultar una habilidad; A o gatillo DERECHO la activa sin espera. La selección de grupo usa 1 segundo o clic contrario. Las fichas de combatientes siguen sus reglas de consulta. Suelta grip/gatillo para cerrar.");
            Add(d, "On-foot exploration only: LEFT stick click and the right wheel open the same full-size local map. RIGHT stick pans; LEFT up/down zooms and left/right rotates. B or LEFT stick click closes it. Centre both sticks after opening or settings; the local map reserves both. Outside it, RIGHT stick click toggles highlights. These shortcuts do not open the Galactic map or Star system map or apply in combat. In the surface left wheel, stick click switches modes. X pauses.", "Sólo al explorar en superficie: clic del stick IZQUIERDO y rueda derecha abren el mismo mapa local completo. Stick DERECHO desplaza; IZQUIERDO hace zoom arriba/abajo y gira a los lados. B o clic IZQUIERDO cierra. Centra ambos tras abrir o cambiar ajustes; el mapa local los reserva. Fuera de él, clic DERECHO alterna el resaltado. No abren Mapa estelar ni Mapa galáctico, ni funcionan en Combates terrestres. En la rueda izquierda terrestre, su clic cambia de modo. X pausa.");
            Add(d, "Galactic and star system maps", "Mapa estelar y Mapa galáctico");
            Add(d, "Space combat controls", "Controles de Combate espacial");
            Add(d, "For On-foot exploration and Ground combat only, enable Draw distance shortcut in Tabletop settings. Rest the left thumb on its capacitive thumbrest and move the right stick: up draws farther, down draws less. No click or squeeze is needed. The right stick remains reserved until centred after releasing the thumbrest. This shortcut is inactive in Galactic map, Star system map and Space combat, preserving their native scene and tactical visibility.", "Sólo para escenas terrestres: activa Atajo de distancia de dibujado en Maqueta. Apoya el pulgar izquierdo en la zona capacitiva y mueve el stick derecho: arriba dibuja más lejos y abajo menos. No pulses ni aprietes. El stick queda reservado hasta centrarlo después de retirar el pulgar. El atajo está inactivo en Mapa estelar, Mapa galáctico y Combate espacial, conservando su visibilidad nativa y táctica.");
            Add(d, "Surface: explore Actions needs one selection; else Party. Combat modes are independent. After switching, centre stick and release opposite trigger. Combatants: any actor; stick or RIGHT trigger opens native info without selecting or moving the camera. Another actor replaces it; centre keeps it. Release grip/trigger or switch closes. Numbers: order; halo: player turn. Actions: point for info; A or RIGHT trigger activates. Native info follows the right skull, facing you, clear of the left wheel.", "Exploración a pie: Acciones exige una selección; si no, Grupo. En Combates terrestres, los modos son independientes. Centra el stick y suelta el gatillo contrario tras cambiar. Combatientes: stick o gatillo DERECHO abre la ficha original sin seleccionar ni mover cámara. Otro actor la sustituye; centrar la mantiene. Soltar grip/gatillo o cambiar cierra. Números: orden; halo: turno aliado. Acciones: apunta para consultar; A o gatillo DERECHO activa. La ficha sigue al servocráneo derecho, mirando hacia ti y libre de la rueda izquierda.");
            Add(d, "In Ground combat only, double-click the same valid ground destination within 0.35 seconds. At least one click must have produced an accepted native move for the same selected actor in the same turn. The mod adds no movement order or action-point cost: it enters the actor head view and stays there as movement continues. Invalid paths, abilities, enemy turns and deployment never trigger it. A normal click does not exit an existing head view. B or bringing both gripped hands together exits. Configure it under Advanced settings > Tabletop.", "Sólo en Combates terrestres: doble clic en el mismo destino válido en 0,35 segundos. Al menos un clic debe haber generado un movimiento nativo aceptado para el mismo actor seleccionado y turno. El mod no añade órdenes ni coste de puntos: entra en primera persona y la mantiene durante el movimiento. Rutas inválidas, habilidades, turnos enemigos y despliegue no la activan. Un clic normal no sale de primera persona. B o juntar ambas manos con los grips sale. Se configura en Configuración avanzada > Maqueta.");
            Add(d, "Optional; on by default. One click keeps normal movement.", "Opcional; activado por defecto. Un clic mueve normalmente.");
            Add(d, "Right trigger: double-click a move destination", "Gatillo derecho: doble clic en un destino");
            Add(d, "Ground combat: move into head view", "Combates terrestres: mover en primera persona");
            Add(d, "Drag from ground or a controllable character, then release. The group is framed slightly farther away than an individual. Loading a game or area frames the present party once, relative to its floor; distant or unloaded actors do not pull the camera away. Ground combat starts looking steeply down over the group. Dialogue and cutscenes keep their close framing; other UI returns restore the previous view. Manual camera input cancels pending framing. No rectangle or party framing in navigation maps or Space combat.", "Arrastra desde el suelo o un personaje controlable y suelta. El grupo se encuadra algo más lejos que un personaje. Al cargar una partida o escenario se enfoca una vez al grupo presente, relativo a su suelo; actores lejanos o descargados no alejan la cámara. Al comenzar Combates terrestres se empieza mirando al grupo desde arriba. Diálogos y cinemáticas conserva su encuadre cercano; otras ventanas restauran la vista previa. Mover la cámara cancela el encuadre pendiente. Los mapas y Combate espacial no usan rectángulo ni encuadre de grupo.");
            Add(d, "On foot: release to select and frame.", "A pie: suelta para seleccionar y enfocar.");
            Add(d, "In On-foot exploration and Ground combat, double-click the same character within 0.35 seconds. Its model is hidden from VR eyes and its turns are smoothed; your head remains immediate. B exits if no menu owns Back. Bring both gripped hands together to return to the table. In Ground combat, an optional double-click on a valid move destination also enters head view after native movement is accepted. Navigation maps and Space combat exclude head view.", "En Exploración a pie y Combates terrestres, haz doble clic en el mismo personaje en 0,35 segundos. Su modelo se oculta y sus giros se suavizan; tu cabeza responde al instante. B sale si ningún menú usa Volver. Junta ambas manos con los grips para volver a la mesa. En Combates terrestres, una opción permite entrar con doble clic en un destino válido tras aceptarse el movimiento nativo. Los mapas y Combate espacial excluyen primera persona.");
            Add(d, "Character: head view. B or zoom out: exit.", "Personaje: primera persona. B o alejar: salir.");
            Add(d, "Point with the right skull and press/release its trigger; A also clicks. On foot, character framing is similar to the group view; group framing is slightly farther away. Height follows the actual character floor. UI clicks never move the camera. Navigation maps keep native selection/travel. Space combat keeps native routes and targeting; ship clicks never refocus or enter head view.", "Apunta con el servocráneo derecho y pulsa/suelta su gatillo; A también hace clic. En Exploración a pie, el encuadre individual es parecido al del grupo, algo más alejado. La altura sigue el suelo real del personaje. Pulsar la interfaz no mueve la cámara. Los mapas conservan selección y viajes nativos. Combate espacial conserva rutas y objetivos; pulsar una nave no reenfoca ni entra en primera persona.");
            Add(d, "Ground: moderate focus. Space: native orders.", "Tierra: enfoque moderado. Espacio: órdenes.");
            Add(d, "Surface: stick click swaps. Space: weapons.", "Tierra: clic cambia modo. Espacio: armas.");
            // Spatial-domain scope reviewed together for both canonical help surfaces.
            Add(d, "On the surface, double-click the same character within 0.35 seconds. Its model is hidden from VR eyes and actor turns ease smoothly; physical head motion stays immediate. B exits when no menu owns Back. Bringing both gripped hands together or choosing a Party portrait outside combat also returns to the table. Combatants only shows information. Head view is unavailable in navigation maps and space battles.", "En superficie, haz doble clic en el mismo personaje en 0,35 segundos. Su modelo se oculta en VR y sus giros se suavizan; tu cabeza responde al instante. B sale si ningún menú usa Volver. Juntar ambas manos con los grips o elegir un retrato de Grupo fuera de combate también vuelve a la mesa. Combatientes sólo muestra datos. No hay primera persona en mapas de navegación ni batallas espaciales.");
            Add(d, "Surface only. B or zoom out: exit.", "Sólo en superficie. B o alejar zoom: salir.");
            Add(d, "On the surface, drag from ground or a controllable character; release to select and frame the group. Loading a game or area frames it once. Battle starts with a medium-height group view, relative to the characters, looking steeply down. Dialogues keep their own close framing; other menu or tutorial returns restore the previous view. Manual camera input cancels pending framing. No group rectangle or group framing applies to navigation maps or space battles.", "En superficie, arrastra desde el suelo o un personaje controlable; suelta para seleccionar y encuadrar el grupo. Una carga lo encuadra una vez. El combate empieza a altura media relativa, mirando hacia el suelo. Los diálogos usan su encuadre cercano; volver de otros menús o tutoriales conserva la vista anterior. Mover la cámara cancela el encuadre pendiente. No hay rectángulo ni encuadre de grupo en mapas de navegación o batallas espaciales.");
            Add(d, "Surface only. Release to select and frame.", "Sólo en superficie. Suelta: selecciona y encuadra.");
            Add(d, "On the surface and in space battles, rotate both servo-skulls or change their separation while holding both grips. Each table has fixed comfort limits; space scale is relative to the ship and does not change your surface zoom setting. Bringing the hands together also leaves surface character head view. Map and management panels use their placement settings instead of these gestures.", "En superficie y en batallas espaciales, gira los dos servocráneos o cambia su separación manteniendo ambos grips. Cada mesa tiene límites de comodidad; la escala espacial depende de la nave y no cambia el zoom de superficie. Juntar las manos también sale de la primera persona del personaje. Los paneles de mapas y gestión usan sus ajustes de posición, en lugar de estos gestos.");
            Add(d, "In surface and space battles, orbit the table at your turn-speed setting, preserving zoom and centre. Surface dialogues also allow it; head view follows the character instead. In an open wheel its own stick selects abilities or entries; only the surface left wheel switches modes with stick click. The local map has its own zoom/turn controls. Grips, UI presses and selections take priority. Centre the stick after a grip or menu.", "En superficie y en batallas espaciales, gira la mesa a tu velocidad configurada, conservando zoom y centro. También funciona en diálogos de superficie; la primera persona sigue al personaje. En una rueda abierta, su stick elige habilidades u opciones; sólo la rueda izquierda terrestre cambia de modo con clic. El mapa local tiene su propio zoom/giro. Grips, clics y selección tienen prioridad. Centra el stick después de un grip o menú.");
            Add(d, "Right wheel", "Rueda derecha");
            Add(d, "Surface: explore Actions needs one selection; else Party. Combat modes are independent. After switching, centre stick and release opposite trigger. Combatants: any actor; stick or RIGHT trigger opens native info without selecting or moving the camera. Another actor replaces it; centre keeps it. Release grip/trigger or switch closes. Numbers: order; halo: player turn. Actions: point for info; A or RIGHT trigger activates.", "Superficie: Acciones exige una selección al explorar; si no, Grupo. En combate, modos independientes. Centra stick y suelta gatillo contrario tras cambiar. Combatientes: todos; stick o gatillo DERECHO abre la ficha original sin seleccionar ni mover cámara. Otro actor la sustituye; centrar la mantiene. Soltar grip/gatillo o cambiar cierra. Números: orden; halo: turno aliado. Acciones: consulta al señalar; A o gatillo DERECHO activa.");
            Add(d, "Surface modes. Combat info stays; A/trigger uses abilities.", "Modos terrestres. Ficha fija; A/gatillo: habilidad.");
            Add(d, "Surface exploration only: LEFT stick click and the right wheel open the same full-size local map. RIGHT stick pans; LEFT up/down zooms and left/right rotates. B or LEFT stick click closes it. Centre both sticks after opening or settings; the local map reserves both. Outside it, RIGHT stick click toggles highlights. These shortcuts do not open the galactic/system map or apply in combat. In the surface left wheel, stick click switches modes. X pauses.", "Sólo al explorar en superficie: clic del stick IZQUIERDO y rueda derecha abren el mismo mapa local completo. Stick DERECHO desplaza; IZQUIERDO hace zoom arriba/abajo y gira a los lados. B o clic IZQUIERDO cierra. Centra ambos tras abrir o cambiar ajustes; el mapa local los reserva. Fuera de él, clic DERECHO alterna el resaltado. No abren Mapa estelar ni Mapa galáctico, ni funcionan en Combates terrestres. En la rueda izquierda terrestre, su clic cambia de modo. X pausa.");
            Add(d, "Surface only. Local map / object highlights.", "Sólo en superficie. Mapa local / resaltar objetos.");
            Add(d, "For surface scenes only, enable Draw distance shortcut in Tabletop settings. Rest the left thumb on its capacitive thumbrest and move the right stick: up draws farther, down draws less. No click or squeeze is needed. The right stick remains reserved until centred after releasing the thumbrest. This shortcut is inactive in galactic/system maps and space battles, preserving their native scene and tactical visibility.", "Sólo para escenas terrestres: activa Atajo de distancia de dibujado en Maqueta. Apoya el pulgar izquierdo en la zona capacitiva y mueve el stick derecho: arriba dibuja más lejos y abajo menos. No pulses ni aprietes. El stick queda reservado hasta centrarlo después de retirar el pulgar. El atajo está inactivo en los mapas galáctico/de sistema y las batallas espaciales, conservando su visibilidad nativa y táctica.");
            Add(d, "Surface only. Optional; off by default.", "Sólo en superficie. Opcional; desactivado de inicio.");

            Add(d, "Surface: focus. Space: native clicks and orders.", "Superficie: encuadrar. Espacio: clics y órdenes nativas.");
            Add(d, "Point with the right skull and press/release its trigger; A also clicks. Surface characters receive moderate framing relative to their floor, including raised walkways. UI and dialogue clicks never move the camera. Maps preserve native selection and double-click travel. Space battles use native tactical selection, routes and targeting; clicking a ship never focuses the camera or opens head view.", "Apunta con el cráneo derecho y pulsa/suelta su gatillo; A también hace clic. Los personajes de superficie se encuadran a distancia moderada respecto a su suelo, incluidas pasarelas. Los clics de interfaz y diálogo no mueven la cámara. Los mapas conservan la selección y el viaje por doble clic nativos. En batalla espacial se usan selección, rutas y objetivos tácticos; pulsar una nave no centra la cámara ni activa primera persona.");
            Add(d, "Surface: move group. Space: use the pointer.", "Superficie: mover grupo. Espacio: usa el puntero.");
            Add(d, "Move the selected group in surface exploration. Follow moving characters enables smooth travel and quicker direction alignment; off keeps the table still. A held stick keeps its starting heading: centre it to adopt the new heading. HUD hover does not stop movement; clicks and menus do. Space battles use native pointer orders, never stick piloting. On map panels the stick scrolls native UI or zooms the map when the native camera permits it.", "Mueve el grupo seleccionado al explorar en superficie. Seguir personajes añade desplazamiento suave y alineación más rápida; desactivado mantiene la mesa quieta. Mantener el stick conserva la dirección inicial: céntralo para adoptar otra. Pasar sobre el HUD no detiene el movimiento; los clics y menús sí. En batalla espacial se dan órdenes con el puntero, sin pilotar con el stick. En mapas, el stick desplaza la interfaz o hace zoom si lo permite la cámara nativa.");
            Add(d, "Same table gestures in surface and space battles.", "Mismos gestos de mesa en superficie y batallas espaciales.");
            Add(d, "Hold either grip and move the hand to reposition the tabletop; release to finish. Physical head motion remains free. The same gestures work in space battles and surface dialogue scenes. Space battles start with a ship-relative frame and do not follow ship turns automatically. Use Advanced settings > Space > Frame active ship for explicit framing. Map and management panels use their own placement settings; grips do not drag them.", "Mantén un grip y mueve la mano para desplazar la maqueta; suelta para terminar. La cabeza se mueve libremente. Funciona igual en batallas espaciales y diálogos en superficie. Las batallas espaciales comienzan con encuadre relativo a la nave y no sigue sus giros automáticamente. Usa Configuración avanzada > Espacio > Encuadrar nave activa para centrarla. Los paneles de mapas y gestión tienen ajustes propios; los grips no los arrastran.");
            Add(d, "Surface: menus. Space: ship-post abilities.", "Superficie: menús. Espacio: habilidades de puestos.");
            Add(d, "Hold right grip and trigger for 0.15 seconds. On the surface, choose a menu by holding its stick sector for 1 second, or point and click with the LEFT trigger. In space battles this wheel contains native ship-post abilities: point to preview original information, then A or LEFT trigger activates; no dwell activation. Grey entries cannot execute. Release the opening controls to cancel. All four opening buttons held together reserve VR settings.", "Mantén grip y gatillo derechos durante 0,15 segundos. En superficie, elige un menú manteniendo su sector con el stick 1 segundo, o apunta y pulsa el gatillo IZQUIERDO. En batalla espacial esta rueda contiene habilidades nativas de puestos: señala para ver su ficha y activa con A o gatillo IZQUIERDO, sin activación por permanencia. Las opciones grises no se ejecutan. Suelta la combinación para cancelar. Los cuatro botones juntos reservan la configuración VR.");
            Add(d, "Surface: actions/party. Space: weapons/actions.", "Superficie: acciones/grupo. Espacio: armas/acciones.");
            Add(d, "Hold left grip and trigger for 0.15 seconds. Surface modes switch with left stick click: Actions, Party or Combatants. Space battles use native weapons and actions of the active unit, with no terrestrial mode switch. Point with the stick or RIGHT skull to preview an ability; A or RIGHT trigger activates, without a dwell timer. Party selection uses 1 second or opposite click. Combatant information follows the separate inspection rules. Release grip/trigger to close.", "Mantén grip y gatillo izquierdos durante 0,15 segundos. En superficie, el clic del stick alterna Acciones, Grupo o Combatientes. En batalla espacial aparecen armas y acciones nativas de la unidad activa, sin alternar esos modos terrestres. Señala con stick o cráneo DERECHO para consultar una habilidad; A o gatillo DERECHO la activa sin espera. La selección de grupo usa 1 segundo o clic contrario. Las fichas de combatientes siguen sus reglas de consulta. Suelta grip/gatillo para cerrar.");
            Add(d, "Galactic and system maps", "Mapas galáctico y de sistema");
            Add(d, "Point, click and native map controls", "Apuntado, clic y controles nativos del mapa");
            Add(d, "Two panels with independent placement.", "Dos paneles con posición independiente.");
            Add(d, "Both maps stay inside VR as native management panels. Use the original objects, routes, filters, travel confirmations and Back controls. Their size, distance, proportions and position are under Advanced settings > Space and are included in HUD presets. Native edge movement and scroll/zoom follow the map camera rules. Map double-clicks keep their original function; there is no head view, group movement or selection rectangle here.", "Ambos mapas permanecen en VR como paneles de gestión nativos. Usa sus objetos, rutas, filtros, confirmaciones de viaje y controles de volver. Tamaño, distancia, proporciones y posición están en Configuración avanzada > Espacio y se guardan en los presets de HUD. El desplazamiento por bordes y el scroll/zoom siguen las reglas de la cámara del mapa. El doble clic conserva su función original; aquí no hay primera persona, movimiento de grupo ni selección rectangular.");
            Add(d, "Space battle controls", "Controles de batalla espacial");
            Add(d, "Table gestures + native tactical pointer", "Gestos de mesa y puntero táctico nativo");
            Add(d, "Left: weapons. Right: ship posts. A or opposite trigger.", "Izquierda: armas. Derecha: puestos. A o gatillo contrario.");
            Add(d, "Keep the normal grip gestures and left-stick table rotation/tilt. Point and click to use the original movement, orientation, weapon arcs and target confirmations. Left wheel: weapons/actions; right: ship-post abilities. Native unit, turn, resources and cooldowns decide what can execute, including auxiliary units. Both wheels preview abilities and confirm with A or the opposite trigger. End turn, shields, objectives and important warnings stay in the original HUD. B cancels through the native controls.", "Usa grips y stick izquierdo para mover, girar e inclinar la mesa. El puntero conserva rutas, orientación, arcos y confirmaciones nativos. Izquierda: armas/acciones; derecha: puestos. Unidad, turno, recursos y recargas deciden qué se puede usar, también en auxiliares. Señala para ver la ficha; A o gatillo contrario activa. Fin de turno, escudos, objetivos y avisos siguen en el HUD original. B cancela.");
            Add(d, "Smooth turns. B or zoom out: exit.", "Giro suave. B o alejar zoom: salir.");
            Add(d, "Double-click the same character within 0.35 seconds. Its model is hidden from VR eyes and actor turns ease smoothly. Physical head motion stays immediate. B exits head view when no menu owns Back. Bringing both gripped hands together also returns to the table, as does selecting a Party portrait outside combat. Combatants only shows information.", "Doble clic en el mismo personaje en 0,35 segundos. Su modelo se oculta en VR y sus giros se suavizan; tu cabeza responde al instante. B sale de primera persona si ningún menú necesita Atrás. Juntar las manos con ambos grips también vuelve a la maqueta, igual que elegir un retrato de Grupo fuera de combate. Combatientes sólo muestra información.");
            Add(d, "Group frame after loads; tactical frame at battle start.", "Grupo tras cargar; vista táctica al iniciar combate.");
            Add(d, "Drag from ground or a controllable character; release to select and frame the group. Loading a game or area frames the group. Battle starts with a medium-height group view, relative to the characters, looking steeply down. Dialogues keep their specific close framing. Other menu or tutorial returns restore your previous view. Manual camera input cancels pending automatic framing.", "Arrastra desde el suelo o un personaje controlable; suelta para seleccionar y encuadrar el grupo. Cargar partida o zona enfoca al grupo. El combate empieza a altura media relativa a los personajes, mirando bastante al suelo. Los diálogos conservan su encuadre cercano. Otros regresos de menús o tutoriales recuperan la vista anterior. Mover la cámara cancela el encuadre automático pendiente.");
            Add(d, "Stick click: modes. Abilities: A or opposite trigger.", "Clic stick: modos. Habilidad: A o gatillo contrario.");
            Add(d, "Hold to open; click left stick to switch modes. Actions: point with stick or RIGHT skull to preview native details; A or RIGHT trigger activates, without a dwell timer. Party: hold sector 1 second or point and click to select/focus. Combatants: stick direction or RIGHT trigger opens native info; centring keeps it. Release the opening grip/trigger or switch mode to close wheel details.", "Mantén para abrir; clic en stick izquierdo alterna modos. Acciones: apunta con stick o cráneo DERECHO para ver la ficha original; A o gatillo DERECHO activa, sin espera. Grupo: mantén un sector 1 segundo o apunta y haz clic para seleccionar/enfocar. Combatientes: dirección del stick o gatillo DERECHO abre la ficha; centrar la mantiene. Soltar grip/gatillo de apertura o cambiar de modo cierra los detalles.");
            Add(d, "Combat info stays. Abilities: A or opposite trigger.", "Ficha fija en combate. Habilidad: A o gatillo contrario.");
            Add(d, "Explore: Actions needs one selection; otherwise Party. Combat modes are independent; Actions follows the turn. After switching, centre stick and release opposite trigger. Combatants: stick direction or RIGHT trigger opens original info without selection or camera movement. Another actor replaces it; centre keeps it. Release grip/trigger or switch mode closes. Numbers: order; halo: player turn. Actions: point to preview; A or RIGHT trigger activates.", "Explorar: Acciones exige una selección; si no, Grupo. En combate ambos modos son independientes; Acciones sigue el turno. Tras cambiar, centra stick y suelta gatillo contrario. Combatientes: dirección del stick o gatillo DERECHO abre la ficha sin seleccionar ni mover cámara. Otro actor la sustituye; centrar stick la mantiene. Soltar grip/gatillo o cambiar modo cierra. Nunca gris por bando o turno. Número: orden; halo: turno del jugador. Acciones: apunta para ver; A o gatillo DERECHO activa.");
            Add(d, "Outside combat: LEFT stick click and the right wheel open the same full-size map. RIGHT stick pans; LEFT up/down zooms and left/right rotates. B or LEFT stick click closes it. Centre both sticks after opening or settings; the map reserves both from gameplay. Outside the map, RIGHT stick click toggles highlights. In the open left wheel its stick click switches modes; X pauses.", "Fuera de combate: clic IZQUIERDO y rueda derecha abren el mismo mapa completo. Stick DERECHO desplaza; IZQUIERDO hace zoom arriba/abajo y gira izquierda/derecha. B o clic IZQUIERDO cierra. Centra ambos al abrir o volver de ajustes; el mapa reserva los sticks. Fuera del mapa, clic DERECHO activa o desactiva el resaltado. En la rueda izquierda abierta, su clic cambia de modo; X pausa.");
            Add(d, "Secondary click / back / leave head view.", "Clic secundario / atrás / salir de primera persona.");
            Add(d, "Left trigger performs a secondary click. B or the left menu button performs Back/Cancel. B first closes the active settings, wheel or native menu; in gameplay it exits character head view.", "El gatillo izquierdo hace clic secundario. B o menú izquierdo realiza Atrás/Cancelar. B cierra primero los ajustes, rueda o menú nativo abierto; durante la partida sale de primera persona.");
            Add(d, "Stick click: modes. Actions 1 s; combat actors: point.", "Clic: modos. Acciones: 1 s. Actores de combate: apunta.");
            Add(d, "Start on the ground or a controllable character. Release to select and frame the group. Selected characters keep their configured marks. Loading, ending a scene or closing a full-size game menu frames the current selection once after controls return to neutral. Head view is preserved. A camera gesture, group movement or world click cancels pending automatic framing; compact map and portrait previews do not reset the camera.", "Empieza en el suelo o sobre un personaje controlable. Suelta para seleccionar y encuadrar el grupo, conservando sus marcas. Al cargar, terminar una escena o cerrar un menú completo, encuadra una vez la selección cuando los controles vuelven al centro. Respeta la primera persona. Un gesto de cámara, mover el grupo o hacer clic en el escenario cancela el encuadre pendiente. El mapa compacto y las consultas de retratos no recolocan la cámara.");
            Add(d, "Group framing after loads, scenes and full menus.", "Enfoca al grupo tras cargas, escenas y menús.");
            Add(d, "Hold to open. Click the left stick to switch actions and portraits. Centre it, then hold an action or Party sector for 1 second; centre to cancel the timer. Or aim the RIGHT skull and click its trigger. Release the opening controls only closes the wheel. Party selects and focuses, with native level-up badges. Combatants only previews original information above the left wheel while pointed at, without selection or camera movement. Move off the portrait or centre the stick to hide it. No click or dwell confirmation in Combatants.", "Mantén para abrir. Haz clic en el stick izquierdo para alternar acciones y retratos. Céntralo y mantén una acción o retrato de Grupo 1 segundo; centrar cancela el tiempo. También puedes apuntar con el servocráneo DERECHO y pulsar su gatillo. Soltar sólo cierra la rueda. Grupo selecciona y enfoca, con el aviso nativo de nivel. Combatientes sólo consulta datos originales encima de la rueda izquierda mientras apuntas, sin seleccionar ni mover la cámara. Aparta el puntero o centra el stick para ocultarlos. Aquí no se confirma con clic ni espera.");
            Add(d, "Stick click: modes. Actions 1 s; actors: point.", "Clic: modos. Acciones: 1 s; actores: apunta.");
            Add(d, "Explore: Actions require one selection; otherwise Party. Combat: opens Actions for the native turn; both modes work independently. After switching, centre the stick and release the opposite trigger. Combatants: all actors show original game information, never grey by turn or allegiance, with order and player-turn halo. Point the RIGHT skull or move the left stick onto a portrait to inspect above the left wheel. Moving away hides the information; the wheel stays open. Triggers and dwell do not confirm. Grey actions are unavailable. End turn is in Actions.", "Al explorar: Acciones exige una selección; si no, Grupo. Combate: abre Acciones del turno nativo; ambos modos son independientes. Tras cambiar, centra el stick y suelta el gatillo contrario. Combatientes muestra datos originales de todos, nunca gris por bando o turno, con orden y halo del turno del jugador. Apunta con el servocráneo DERECHO o lleva el stick izquierdo a un retrato para consultar encima de la rueda izquierda. Apartarlo oculta los datos; la rueda sigue abierta. Gatillos y espera no confirman. Las acciones grises no están disponibles. Terminar turno está en Acciones.");
            Add(d, "Combat portraits: point to inspect; centre to hide.", "Combate: apunta para consultar; centra para ocultar.");
            Add(d, "Outside combat, click the LEFT stick to open the original local map as a small floating panel; click again to close. The right wheel opens its full-size version. In either map, RIGHT stick pans; LEFT up/down zooms and left/right rotates. Centre both sticks after opening or returning from settings. The map reserves both sticks from gameplay. Outside the map, RIGHT stick click toggles object highlights. These shortcuts start with no wheel, scene or window open. In the left wheel, stick click still switches modes. X pauses; Y is unchanged.", "Fuera de combate, haz clic en el stick IZQUIERDO para abrir el mapa local original como panel flotante pequeño; repite para cerrar. La rueda derecha abre la versión completa. En ambos, el stick DERECHO mueve el mapa; el IZQUIERDO hace zoom arriba/abajo y gira izquierda/derecha. Centra ambos al abrir o volver de ajustes. El mapa reserva los dos sticks. Fuera del mapa, clic DERECHO activa o desactiva el resaltado de objetos. Se inicia sin rueda, escena ni ventana abierta. En la rueda izquierda su clic cambia de modo. X pausa; Y no cambia.");
            Add(d, "Map: R pan; L zoom/turn. R-click: highlights.", "Mapa: D mueve; I zoom/giro. Clic D: objetos.");
            Add(d, "Click left stick to switch actions and portraits. Centre it, then hold an action or Party sector 1 second; centre to cancel. Or point the RIGHT skull and click. Release the opening controls only closes the wheel. Party selects and focuses, with level-up badges. Combatants previews native information above the left wheel, without selection or camera movement. Point away or centre to hide. No click or dwell confirmation in Combatants.", "Clic en stick izquierdo: acciones o retratos. Céntralo y mantén una acción o retrato de Grupo 1 segundo; centrar cancela. O apunta con el cráneo DERECHO y haz clic. Soltar sólo cierra. Grupo selecciona y enfoca, con avisos de nivel. Combatientes consulta datos originales encima de la rueda izquierda, sin seleccionar ni mover la cámara. Aparta el puntero o centra el stick para ocultarlos. Aquí no hay confirmación por clic ni espera.");
            Add(d, "Explore: Actions need one selection; otherwise Party. Combat: both modes are independent; Actions use the native turn. After switching, centre stick and release opposite trigger. Combatants: point with RIGHT skull or left stick to show native information; centre/move away hides it without closing. No click or dwell. All actors are available; numbers show turn order and halo marks the player's turn. End turn: Actions.", "Explorar: Acciones exige una selección; si no, Grupo. Combate: ambos modos son independientes; Acciones usa el turno nativo. Tras cambiar, centra el stick y suelta el gatillo contrario. Combatientes: apunta con cráneo DERECHO o stick izquierdo para consultar datos originales; aparta o centra para ocultarlos sin cerrar. Sin clic ni espera. Todos disponibles, nunca gris por bando o turno. Números: orden; halo: turno del jugador. Terminar turno: Acciones.");
            Add(d, "Outside combat: LEFT stick click toggles the compact original map; the right wheel opens it full-size. In either map, RIGHT stick pans; LEFT up/down zooms and left/right rotates. Centre both sticks after opening or settings. The map reserves both from gameplay. Outside the map, RIGHT stick click toggles highlights. Shortcuts require no other wheel, scene or window. Left-wheel stick click switches modes; X pauses.", "Fuera de combate: clic IZQUIERDO abre/cierra el mapa original compacto; la rueda derecha lo abre completo. En ambos mapas, stick DERECHO desplaza; IZQUIERDO hace zoom arriba/abajo y gira izquierda/derecha. Centra ambos al abrir o volver de ajustes. El mapa reserva los sticks. Fuera del mapa, clic DERECHO activa o desactiva el resaltado. Los atajos requieren que no haya otra rueda, escena o ventana. En la rueda izquierda, su clic cambia de modo; X pausa.");
            // select
            Add(d, "Select and focus", "Seleccionar y enfocar");
            Add(d, "Right trigger: click", "Gatillo derecho: clic");
            Add(d, "Frame above the character at a moderate distance.", "Enfoca al personaje a distancia moderada.");
            Add(d, "Aim the right servo-skull and press/release. Camera height follows the selected character's floor, including raised walkways. Focus keeps your miniature scale; obstacles may raise the view, but cannot force extreme close-ups. If no safe framing fits, your current view stays. A is also a primary click. Dialogue answers and game UI use the pointer without moving the camera.", "Apunta con el servocráneo derecho y pulsa y suelta. La altura sigue el suelo del personaje, incluso en pasarelas. Conserva la escala de maqueta; los obstáculos pueden elevar la vista, pero no acercarla en exceso. Si no cabe un encuadre seguro, se mantiene la vista. A también hace clic principal. Las respuestas de diálogo y la interfaz usan el puntero sin mover la cámara.");
            // head-view
            Add(d, "Character head view", "Primera persona");
            Add(d, "Right trigger: double-click", "Gatillo derecho: doble clic");
            Add(d, "Smooth actor turns. Zoom out to exit.", "Giro suave. Aleja el zoom para salir.");
            Add(d, "Release twice on the same character within 0.35 seconds. Selection is immediate; focus briefly waits for the second click. Your model is hidden only from the VR eyes. Actor turns ease smoothly; physical head motion stays immediate. Left-stick table rotation does not apply here. Both grips and hands together return to the table, as does choosing a Party portrait outside combat. Combatants only displays information.", "Suelta dos veces sobre el mismo personaje en 0,35 s. Selecciona al instante; el enfoque espera brevemente el segundo clic. Tu modelo se oculta sólo en VR. Su giro se suaviza; tu cabeza responde al instante. Aquí no gira el stick izquierdo. Junta las manos con ambos grips para volver a la maqueta; también puedes elegir un retrato de Grupo fuera de combate. Combatientes sólo muestra datos.");
            // drag-select
            Add(d, "Select a group", "Seleccionar grupo");
            Add(d, "Right trigger: hold and drag", "Gatillo derecho: mantener y arrastrar");
            Add(d, "Frame the group. Also automatic after loading.", "Enfoca al grupo, también tras cargar.");
            Add(d, "Start on the ground or a controllable character. Release to select and frame the group. Selected characters keep their configured selection marks. A real saved/new-game load frames the current selection once when ready, at the same moderate distance. This waits through help and scenes; starting a camera gesture, group movement or world click cancels the automatic framing.", "Empieza en el suelo o sobre un personaje controlable. Suelta para seleccionar y encuadrar el grupo. Los seleccionados mantienen sus marcas configuradas. Al cargar o iniciar una partida, encuadra una vez la selección a distancia moderada cuando esté lista. Espera a que terminen las ayudas y escenas. Mover la cámara, mover el grupo o hacer clic en el escenario cancela ese enfoque automático.");
            // group-move
            Add(d, "Move the group", "Mover el grupo");
            Add(d, "Right stick", "Stick derecho");
            Add(d, "Optional smooth follow with quicker turn alignment.", "Seguimiento suave y giro ágil opcionales.");
            Add(d, "Move the selected group in exploration. Follow moving characters in Tabletop settings enables smooth travel and quicker alignment toward the route; off keeps the table still. With follow or head view, a held stick keeps its starting heading: centre it to adopt the new heading. Hovering over HUD does not stop movement; actual clicks and menus do. Combat keeps tactical pointer movement.", "Mueve el grupo seleccionado al explorar. Seguir a los personajes en Maqueta activa el avance suave y la orientación hacia la ruta; desactivado, la mesa queda quieta. Con seguimiento o en primera persona, mantener el stick conserva su rumbo inicial: céntralo para adoptar otro rumbo. Pasar sobre el HUD no detiene el movimiento; los clics y menús sí. En combate se mueve con el puntero táctico.");
            // table-move
            Add(d, "Move the table", "Mover la mesa");
            Add(d, "Either grip: hold and move", "Un grip: mantener y mover");
            Add(d, "Reposition the view, including dialogue scenes.", "Ajusta la vista, también en diálogos.");
            Add(d, "Release to finish. Physical head movement remains free. Dialogue scenes start higher above the formation member's head, looking gently down toward the ground. Use the same table gestures to reposition them. Taking manual control after loading cancels any pending automatic group framing.", "Suelta para terminar. Puedes mover libremente la cabeza. Los diálogos parten de una vista elevada sobre la cabeza de un miembro del grupo, mirando un poco hacia el suelo. Usa los mismos gestos para recolocarla. Tomar el control manual tras cargar cancela el enfoque automático pendiente del grupo.");
            // rotate-zoom
            Add(d, "Rotate and zoom", "Girar y acercar");
            Add(d, "Both grips: hold", "Ambos grips: mantener");
            Add(d, "Turn to rotate. Apart: closer. Together: farther.", "Gira. Separa para acercar; junta para alejar.");
            Add(d, "Rotate the pair of servo-skulls or change their separation, within the fixed comfort limits. Bringing them together also leaves character head view.", "Gira ambos servocráneos o cambia su separación, dentro de los límites fijos de comodidad. Juntarlos también permite salir de la vista en primera persona.");
            // tilt
            Add(d, "Rotate / tilt the table", "Girar / inclinar mesa");
            Add(d, "Left stick", "Stick izquierdo");
            Add(d, "Left/right: rotate. Up/down: tilt.", "Izq./der.: giro. Arriba/abajo: inclinación.");
            Add(d, "Smoothly orbit the table at your turn-speed setting. Zoom and view centre are preserved. Works in gameplay and dialogue scenes; head view follows the character instead. In the open left wheel, this stick selects; clicking it switches modes. Grips, selection and UI presses take priority. Centre the stick after using a grip or closing a menu.", "Gira suavemente la mesa a la velocidad configurada, conservando zoom y centro. Funciona en la partida y en diálogos; en primera persona se sigue al personaje. En la rueda izquierda abierta, el stick elige y su clic cambia de modo. Los grips, la selección y los clics de interfaz tienen prioridad. Centra el stick tras usar un grip o cerrar un menú.");
            // radial-right
            Add(d, "Right menu wheel", "Rueda de menús derecha");
            Add(d, "Right grip + trigger: 0.15 s", "Grip + gatillo derechos: 0,15 s");
            Add(d, "Stick: hold sector 1 s. Release: cancel.", "Mantén un sector 1 s. Soltar: cancelar.");
            Add(d, "Hold to project game menus from the RIGHT skull, in and out of combat. Grey options cannot execute. Opened service windows are enlarged, with CLOSE below. Centre the right stick, then hold a sector for 1 second until its progress ring fills. Changing sector or centring cancels the timer. Or aim the LEFT skull and click its trigger; this takes priority. Release the opening controls to cancel or rearm. All four buttons open settings instead.", "Mantén para proyectar los menús desde el cráneo DERECHO, dentro y fuera de combate. Las opciones grises no se activan. Las ventanas se amplían y tienen CERRAR debajo. Centra el stick derecho y mantén un sector 1 segundo hasta llenar el anillo. Cambiar de sector o centrar cancela el tiempo. O apunta con el cráneo IZQUIERDO y pulsa su gatillo; tiene prioridad. Suelta los controles para cancelar o rearmar. Los cuatro botones abren ajustes.");
            // radial-left
            Add(d, "Left wheel · modes", "Rueda izquierda · modos");
            Add(d, "Left grip + trigger: 0.15 s", "Grip + gatillo izquierdos: 0,15 s");
            Add(d, "Stick click: switch. Hold sector 1 s.", "Clic stick: cambiar. Sector: mantener 1 s.");
            Add(d, "Hold both controls to open. Click the left stick to switch actions and portraits. Centre it, then hold a sector for 1 second to activate; centre to cancel the timer. Or aim the RIGHT skull and click its trigger. Release the opening controls only closes the wheel. Party selects and focuses; its level-up badge matches the game. Combatants opens the game's original information window, without selection or camera movement. Release controls before reopening. All four buttons take priority.", "Mantén ambos controles para abrir. Haz clic en el stick izquierdo para alternar acciones y retratos. Céntralo y mantén un sector 1 segundo para activar; centrar cancela el tiempo. O apunta con el cráneo DERECHO y pulsa su gatillo. Soltar los controles sólo cierra la rueda. Grupo selecciona y enfoca; muestra el icono original de subida de nivel. Combatientes abre la información original del juego sin seleccionar ni mover la cámara. Suelta antes de reabrir. Los cuatro botones tienen prioridad.");
            // radial-left-modes
            Add(d, "Left wheel: mode rules", "Rueda izquierda: reglas");
            Add(d, "Left stick click: switch", "Clic stick izquierdo: cambiar");
            Add(d, "Actions / characters, without releasing the hold.", "Acciones / personajes, sin soltar.");
            Add(d, "Explore: Actions require one selection; otherwise Party. Combat: opens Actions for the native turn; both modes work independently. After switching, centre the stick and release the opposite trigger. Combatants: all actors show original game information, never grey by turn or allegiance, with order and player-turn halo. Point to preview; dwell or click keeps the window open, without selection or camera movement. Grey actions are unavailable. End turn is in Actions.", "Exploración: Acciones exige una selección; si no, Grupo. Combate: Acciones del turno actual; ambos modos son independientes. Tras cambiar, centra el stick y suelta el gatillo opuesto. Combatientes: información original de todos, nunca gris por bando o turno, con orden y halo del turno aliado. Apunta para consultar; mantener o hacer clic conserva la ventana, sin seleccionar ni mover la cámara. Gris: acción no disponible. Fin de turno está en Acciones.");
            // exploration-shortcuts
            Add(d, "Map / reveal objects", "Mapa / resaltar objetos");
            Add(d, "Click left / right stick", "Clic stick izquierdo / derecho");
            Add(d, "Explore only: map / toggle object highlights.", "Sólo al explorar: mapa / alternar resaltado.");
            Add(d, "Click the LEFT stick to open the native map. Click the RIGHT stick to turn object highlighting on or off. These shortcuts work outside combat, with no wheel, scene or window open. In the open left wheel its stick click still switches modes. Highlighting is restored on entering combat, menus or another gesture. X still pauses; Y is unchanged.", "Clic en el stick IZQUIERDO abre el mapa del juego. Clic en el DERECHO activa o desactiva el resaltado de objetos. Sólo fuera de combate, sin rueda, escena ni ventana abierta. Con la rueda izquierda abierta, su clic sigue cambiando de modo. Al entrar en combate, menús u otro gesto, se restaura el resaltado previo. X sigue pausando; Y no cambia.");
            // secondary
            Add(d, "Secondary / back", "Secundario / volver");
            Add(d, "Left trigger / B", "Gatillo izquierdo / B");
            Add(d, "Secondary click / go back or cancel.", "Clic secundario / volver o cancelar.");
            Add(d, "The left trigger performs a secondary click. B or the left menu button performs the game's back/cancel action.", "El gatillo izquierdo hace clic secundario. B o el botón de menú izquierdo ejecutan la acción de volver o cancelar del juego.");
            // pause
            Add(d, "Pause", "Pausa");
            Add(d, "X button", "Botón X");
            Add(d, "Pause or resume the game.", "Pausa o reanuda el juego.");
            Add(d, "Uses the game's pause action when gameplay input is available.", "Usa la pausa del juego cuando los controles de partida están disponibles.");
            // overlay
            Add(d, "VR settings", "Opciones VR");
            Add(d, "Both triggers + grips: 2 s", "Ambos gatillos y grips: 2 s");
            Add(d, "Open or close settings. Takes priority over wheels.", "Abre o cierra. Tiene prioridad sobre ruedas.");
            Add(d, "Hold all four for 2 seconds. Release all four before repeating. This chord cancels either wheel without executing an action. F1 also opens/closes the panel and takes priority over the game's key binding.", "Mantén los cuatro durante 2 s. Suéltalos todos antes de repetir. Esta combinación cancela cualquier rueda sin ejecutar su acción. F1 también abre o cierra el panel y tiene prioridad sobre la asignación de esa tecla en el juego.");
            // overlay-navigation
            Add(d, "Use VR settings", "Usar las opciones VR");
            Add(d, "Point + right trigger", "Apuntar + gatillo derecho");
            Add(d, "Click controls. Stick + A/B also work.", "Clic en controles. También stick + A/B.");
            Add(d, "Release the trigger on a row or control. Right stick navigates/changes values, A enters and B returns. The overlay consumes its input so the game does not act behind it. Language and common image settings are on the first page; Advanced settings keeps every setting and detailed help.", "Suelta el gatillo sobre una fila o control. El stick derecho navega y cambia valores; A entra y B vuelve. El panel captura los controles para que el juego no actúe detrás. El idioma y los ajustes de imagen habituales están en el primer nivel; Configuración avanzada conserva todos los ajustes y la ayuda detallada.");
            // keyboard-settings
            Add(d, "Keyboard settings shortcut", "Atajo de teclado");
            Add(d, "F1", "F1");
            Add(d, "Open or close VR settings and help.", "Abre o cierra las opciones VR y la ayuda.");
            Add(d, "This shortcut takes priority over the game's key binding. A held key triggers it only once and is consumed through release. Detailed help is under Advanced settings > Help · Touch controls.", "Tiene prioridad sobre la asignación de esa tecla en el juego. Mantenerla pulsada sólo lo activa una vez y bloquea esa tecla hasta soltarla. La ayuda detallada está en Configuración avanzada > Ayuda · Controles Touch.");
            // draw-distance
            Add(d, "Draw distance", "Distancia de dibujado");
            Add(d, "Left thumbrest touch + right stick up/down", "Pulgar izq. apoyado + stick der. arriba/abajo");
            Add(d, "Optional shortcut. Off by default.", "Atajo opcional. Desactivado de inicio.");
            Add(d, "Enable Draw distance shortcut in Tabletop settings. Then rest your left thumb on its capacitive thumbrest and move the right stick: up draws farther, down draws less. No click or squeeze is needed. The right stick remains reserved until centred after releasing the thumbrest.", "Activa Atajo de distancia en Maqueta. Apoya el pulgar izquierdo en la zona capacitiva y mueve el stick derecho: arriba dibuja más lejos; abajo, menos. No hace falta pulsar ni apretar. Al retirar el pulgar, el stick derecho sigue reservado hasta que lo centres.");
            Add(d, "ROGUE TRADER  ·  TOUCH CONTROLS AT A GLANCE", "ROGUE TRADER  ·  GUÍA RÁPIDA DE CONTROLES TOUCH");
            Add(d, "Detailed help: Advanced settings > Help · Touch controls", "Ayuda detallada: Configuración avanzada > Ayuda · Controles Touch");
            Add(d, "Touch controls", "Controles Touch");
            Add(d, "Touch controls at a glance", "Guía rápida de controles Touch");
            Add(d, "Help · Touch controls", "Ayuda · Controles Touch");
            Add(d, "Animated guide to the current Touch controls and the F1 shortcut. You can return here at any time.", "Guía animada de los controles Touch y del atajo F1. Puedes consultarla en cualquier momento.");
            Add(d, "CLOSE", "CERRAR");
            Add(d, "Select · release right trigger", "Seleccionar · suelta gatillo derecho");
            Add(d, "LIMIT · ", "LÍMITE · ");
            Add(d, "Rotate / zoom", "Girar / zoom");
            Add(d, "Rotate · left stick", "Girar · stick izquierdo");
            Add(d, "Tilt", "Inclinar");
            Add(d, "Release grips", "Suelta los grips");
            Add(d, "Move table", "Mover mesa");
        }
    }
}


