using System.Collections.Generic;
namespace RTMaquetaXR { internal static partial class ModLocalization {
static partial void AddRelease52(Dictionary<string,string> d) {
Add(d, "READY  /  ENTERING THE GAME", "LISTO  /  ENTRANDO EN LA PARTIDA");
Add(d, "Right stick click · show / hide controls", "Clic del stick derecho · mostrar / ocultar controles");
Add(d, "Click · controls", "Clic · controles");
Add(d, "Control reminders", "Recordatorio de controles");
Add(d, "Short RIGHT stick click", "Clic corto del stick DERECHO");
Add(d, "Hidden at launch. Click to show or hide in playable scenes.", "Ocultas al arrancar. Pulsa para mostrarlas u ocultarlas durante el juego.");
Add(d, "Short RIGHT stick click toggles the centred controls reminder in On-foot exploration, Ground combat and Space combat. It stays hidden in menus, maps and dialogue. In exploration, hold the RIGHT stick click for more than half a second to highlight objects until released; a hold does not toggle help.", "Un clic corto del stick DERECHO alterna la ayuda centrada en Exploración a pie, Combates terrestres y Combate espacial. Se oculta en menús, mapas y diálogos. En exploración, mantén el clic DERECHO más de medio segundo para resaltar objetos hasta soltarlo; mantenerlo no alterna la ayuda.");
Add(d, "Release to select; camera stays.", "Suelta para seleccionar; la cámara no se mueve.");
Add(d, "Drag from ground or a controllable character and release to select. Selection never moves the camera, including wheel selection. Double-click frames a character or ship; a deep two-second trigger hold enters first person. Loading frames the group once, at its relative floor height. Ground combat starts with a steep overhead group view.", "Arrastra desde el terreno o un personaje controlable y suelta para seleccionar. La selección nunca mueve la cámara, tampoco desde las ruedas. El doble clic encuadra un personaje o nave; un gatillo profundo de dos segundos entra en primera persona. La carga encuadra el grupo una vez a su altura relativa. El combate terrestre empieza con una vista del grupo muy inclinada desde arriba.");
Add(d, "Map: LEFT click · highlights: hold RIGHT click", "Mapa: clic IZQUIERDO · resaltar: mantener clic DERECHO");
Add(d, "Exploration shortcuts; short RIGHT click toggles help.", "Atajos de exploración; clic DERECHO corto alterna la ayuda.");
Add(d, "LEFT stick click opens the local map; the right wheel opens the same map. In the map, RIGHT stick pans, LEFT stick zooms and rotates; B or LEFT click closes it. Outside the map, hold RIGHT stick click to highlight objects, or click briefly to toggle controls help. These shortcuts never select a route or move a ship.", "Clic del stick IZQUIERDO abre el mapa local; la rueda derecha abre el mismo mapa. En él, el stick DERECHO desplaza y el IZQUIERDO hace zoom y gira; B o clic IZQUIERDO cierra. Fuera del mapa, mantén el clic DERECHO para resaltar objetos o púlsalo brevemente para alternar las ayudas. Estos atajos nunca seleccionan una ruta ni mueven una nave.");
Add(d, "Characters first during ground deployment; actions first during battle.", "Personajes primero durante el despliegue terrestre; acciones primero en batalla.");
Add(d, "Native cards follow the LEFT wheel at a fixed size.", "Las fichas originales siguen a la rueda IZQUIERDA con tamaño fijo.");
Add(d, "LEFT stick turns the first-person view in both ground and space combat.", "El stick IZQUIERDO gira la primera persona en los combates terrestres y espaciales.");
Add(d, "Warp routes use the Star map; planets use the Galactic map.", "Las rutas de disformidad usan el Mapa estelar; los planetas, el Mapa galáctico.");
Add(d, "LEFT stick rotates and tilts the table, with a near-vertical tilt range. In first person it turns the view horizontally, in both ground and space combat. In a wheel the stick selects entries instead; LEFT stick click switches its mode. Grips and UI presses take priority. Centre the stick after a grip or menu.", "El stick IZQUIERDO gira e inclina la maqueta hasta una vista casi vertical. En primera persona gira la vista horizontalmente, tanto en combate terrestre como espacial. En una rueda selecciona opciones; clic IZQUIERDO cambia su modo. Los grips y las pulsaciones de interfaz tienen prioridad. Centra el stick después de usar grips o menús.");
Add(d, "Exploration actions need one selected character. Ground deployment opens Characters first; active ground and space combat open Actions first. LEFT stick click switches modes. Actor information never selects or moves the camera. Centring keeps it; another actor replaces it. Original cards have fixed size and follow the LEFT wheel. Release grip/trigger, press B or switch modes to close.", "Las acciones de exploración necesitan un personaje seleccionado. El despliegue terrestre abre primero Personajes; los combates terrestres y espaciales activos abren primero Acciones. Clic IZQUIERDO cambia el modo. Consultar actores no selecciona ni mueve la cámara. Centrar mantiene la ficha; otro actor la sustituye. Las fichas originales tienen tamaño fijo y siguen a la rueda IZQUIERDA. Suelta grip/gatillo, pulsa B o cambia de modo para cerrar.");
Add(d, "Exploration actions need one selected character. Ground deployment opens Characters first; active ground and space combat open Actions first. LEFT stick click switches modes. Actor information never selects or moves the camera. Centring keeps it; another actor replaces it. Original cards are centred in the view at a stable readable size. Centre the RIGHT stick, then move it up or down to scroll their original content. Release grip/trigger, press B or switch modes to close.", "Las acciones de exploración necesitan un personaje seleccionado. El despliegue terrestre abre primero Personajes; los combates terrestres y espaciales activos abren primero Acciones. Clic IZQUIERDO cambia el modo. Consultar actores no selecciona ni mueve la cámara. Centrar mantiene la ficha; otro actor la sustituye. Las fichas originales están centradas en la vista y mantienen un tamaño legible estable. Centra el stick DERECHO y muévelo arriba o abajo para desplazar su contenido original. Suelta grip/gatillo, pulsa B o cambia de modo para cerrar.");
Add(d, "LEFT stick · turn first-person view", "Stick IZQUIERDO · girar primera persona");
Add(d, "Turn view", "Girar vista");
}}}
