using System.Collections.Generic;
namespace RTMaquetaXR { internal static partial class ModLocalization {
    static partial void AddRelease58(Dictionary<string,string> d) {
        Add(d,"Exploration actions need one selected character. Ground deployment opens Characters first; inspecting a friendly portrait also selects it for placement. Active ground and space combat open Actions first. LEFT stick click switches modes. During the battle, inspection changes neither selection nor camera. Centring keeps the card; another actor replaces it. Original cards stay fixed inside the upper-left part of the HUD. Centre the RIGHT stick, then move it up or down to scroll. Release grip/trigger, press B or switch modes to close.","En Exploración a pie, las acciones necesitan un único personaje seleccionado. El despliegue terrestre abre Personajes; consultar un retrato aliado también lo selecciona para colocarlo. Los combates ya iniciados, terrestres y espaciales, abren Acciones. Pulsar el stick IZQUIERDO cambia de modo. Durante el combate, consultar no cambia la selección ni la cámara. Centrar conserva la ficha; otro actor la sustituye. Las fichas originales quedan fijas dentro de la zona superior izquierda del HUD. Centra el stick DERECHO y muévelo arriba o abajo para desplazar el contenido. Suelta grip/gatillo, pulsa B o cambia de modo para cerrar.");
        Add(d,"B cancels the current interaction: settings, wheel, native window or pending order. In gameplay it also leaves first-person view. The left menu button is Back/Cancel; the left trigger performs a secondary click. On End turn, select with the LEFT stick or opposite Touch, then hold A or the opposite trigger for two seconds. Short clicks and release do not end the turn.","B cancela la interacción actual: opciones, rueda, ventana nativa u orden pendiente. En partida también sale de primera persona. El botón de menú izquierdo es Volver/Cancelar; el gatillo izquierdo hace clic secundario. Para terminar turno, selecciona con el stick IZQUIERDO o el Touch contrario y mantén A o el gatillo contrario dos segundos. Un clic corto o soltar la rueda no termina el turno.");
        Add(d,"Table gestures and LEFT-stick rotation/tilt use ship-relative zoom and keep the board level. Battle entry frames our ship. Click orders without moving the camera; double-click frames the ship along its heading; full RIGHT trigger held for 2 s enters its view. LEFT wheel contains weapons, variants and ship-post abilities; click LEFT stick for the battle ships. RIGHT wheel contains native menus. A or the opposite trigger confirms abilities. On End turn, select with the LEFT stick or opposite Touch, then hold A or the opposite trigger for two seconds. Native rules, resources and cooldowns remain authoritative.","Los gestos y el giro/inclinación del stick IZQUIERDO usan zoom relativo a la nave y mantienen nivelado el tablero. Al entrar se encuadra nuestra nave. Un clic da órdenes sin mover la cámara; el doble clic encuadra siguiendo el rumbo; el gatillo DERECHO a fondo durante 2 s entra en su vista. La rueda IZQUIERDA ofrece armas, variantes y habilidades de puestos; pulsa el stick IZQUIERDO para ver las naves. La DERECHA ofrece menús nativos. A o el gatillo contrario confirma habilidades. Para terminar turno, selecciona con el stick IZQUIERDO o el Touch contrario y mantén A o el gatillo contrario dos segundos. Se conservan las reglas, recursos y tiempos de recarga del juego.");
        Add(d,"Engine optimizations","Optimizaciones del motor");
        Add(d,"Attack calculations","Cálculos de ataques");
        Add(d,"Reachable cells","Casillas alcanzables");
        Add(d,"Weapon and ability bars","Barras de armas y habilidades");
        Add(d,"Tutorials and transitions","Tutoriales y transiciones");
        Add(d,"Effect preparation","Preparación de efectos");
        Add(d,"Tactical geometry","Geometría táctica");
        Add(d,"Combat history","Historial de combate");
        Add(d,"AI diagnostics","Diagnósticos de IA");
        Add(d,"Participants and initiative","Participantes e iniciativa");
        Add(d,"AI evaluation budget · experimental","Presupuesto de IA · experimental");
        Add(d,"Enable this independent optimization package at the next game launch. Each block can be disabled separately. Changes require restarting the game.","Activa este conjunto de optimizaciones en el próximo arranque. Cada bloque se puede desactivar por separado. Los cambios requieren reiniciar el juego.");
        Add(d,"Applied engine blocks","Bloques del motor aplicados");
        Add(d,"Shows applied blocks and saved changes pending a game restart. A block with an incompatible native contract retains the original game path.","Muestra los bloques aplicados y los cambios guardados pendientes de reinicio. Si un bloque es incompatible con el código del juego, se conserva el funcionamiento original.");
        Add(d,"Independent blocks for combat and transition performance. Every change requires a game restart. Timings and results depend on the scene.","Bloques independientes para rendimiento en combate y transiciones. Cada cambio requiere reiniciar el juego. Los tiempos y los resultados dependen de la escena.");
        Add(d,"HOLD A / opposite TRIGGER 2s · END TURN","MANTÉN A / GATILLO contrario 2s · TERMINAR TURNO");
        Add(d,"During deployment, inspecting a friendly portrait also selects that character for placement. During the battle, inspection does not change selection or camera.","Durante el despliegue, consultar un retrato aliado también selecciona ese personaje para colocarlo. Una vez iniciado el combate, consultar no cambia la selección ni la cámara.");
        Add(d,"Reuse audited attack geometry inside the same operation. Conditions, damage and random decisions remain native. Restart the game to apply changes.","Reutiliza la geometría de ataque comprobada dentro de la misma operación. Las condiciones, daños y decisiones aleatorias siguen a cargo del juego. Reinicia el juego para aplicar los cambios.");
        Add(d,"Reuse unchanged movement calculations with invalidation when gameplay state changes. Restart the game to apply changes.","Reutiliza cálculos de movimiento sin cambios y los invalida cuando cambia el estado de juego. Reinicia el juego para aplicar los cambios.");
        Add(d,"Reuse compatible native weapon action models while refreshing the current weapons, abilities and availability. Restart the game to apply changes.","Reutiliza modelos nativos compatibles de acciones de armas mientras actualiza las armas, habilidades y disponibilidad actuales. Reinicia el juego para aplicar los cambios.");
        Add(d,"Avoid redundant native panel layout during transitions, retaining original tutorial and window behaviour. Restart the game to apply changes.","Evita recalcular innecesariamente la distribución de paneles nativos durante transiciones, conservando el funcionamiento original de tutoriales y ventanas. Reinicia el juego para aplicar los cambios.");
        Add(d,"Reuse audited effect component lists in a bounded cache. Structural changes return to the native path. Restart the game to apply changes.","Reutiliza listas comprobadas de componentes de efectos con memoria acotada. Los cambios de estructura recuperan el funcionamiento nativo. Reinicia el juego para aplicar los cambios.");
        Add(d,"Avoid unchanged tactical geometry rebuilds. Movement and attack indicators stay visible. Restart the game to apply changes.","Evita reconstruir geometría táctica que no ha cambiado. Conserva visibles los indicadores de movimiento y ataque. Reinicia el juego para aplicar los cambios.");
        Add(d,"Spread queued combat-history presentation across frames without dropping events or changing combat rules. Restart the game to apply changes.","Reparte entre fotogramas la presentación pendiente del historial de combate, sin perder sucesos ni cambiar las reglas. Reinicia el juego para aplicar los cambios.");
        Add(d,"Skip formatting AI diagnostics when the native logger would discard them. Enabled messages and errors remain available. Restart the game to apply changes.","Evita preparar textos de diagnóstico de IA que el registro nativo descartaría. Conserva los mensajes habilitados y los errores. Reinicia el juego para aplicar los cambios.");
        Add(d,"Reuse participant enumeration within the same initiative operation. Rebuild for the next operation so arrivals and departures stay current. Restart the game to apply changes.","Reutiliza el recorrido de participantes dentro de la misma operación de iniciativa. Lo renueva en la siguiente operación para reflejar incorporaciones y salidas. Reinicia el juego para aplicar los cambios.");
        Add(d,"Experimental: yield between audited AI evaluation iterations. Preserves candidates and resumes the decision; does not lower the game frame rate. Restart the game to apply changes.","Experimental: reparte iteraciones comprobadas de evaluación de IA. Conserva los candidatos y continúa la decisión; no limita los FPS del juego. Reinicia el juego para aplicar los cambios.");
    }
}}
