using System.Collections.Generic;
namespace RTMaquetaXR { internal static partial class ModLocalization {
static partial void AddRelease61(Dictionary<string,string> d) {
d["Both triggers + grips: 1 s"] = "Ambos gatillos + grips: 1 s";
d["Hold both triggers and both grips together for 1 s to open or close settings. Release all four before repeating. A completed settings chord closes the wheel without executing its action. F1 also toggles settings and takes priority over game bindings."] = "Mantén ambos gatillos y grips durante 1 s para abrir o cerrar los ajustes. Suelta los cuatro antes de repetir. Completar la combinación cierra la rueda sin ejecutar su opción. F1 también abre/cierra los ajustes y tiene prioridad sobre el juego.";
d["LEFT stick / A / RIGHT trigger: hold 1 s"] = "Stick IZQUIERDO / A / gatillo DERECHO: mantener 1 s";
d["Three independent ways to end the turn."] = "Tres formas independientes de terminar turno.";
d["In Ground combat and Space combat, choose End turn on the LEFT wheel. Keep the LEFT stick over its skull for 1 s, without any other confirmation. Alternatively, aim with the RIGHT skull and hold its trigger for 1 s, or hold A for 1 s on the selected option. Each method works alone. Releasing early cancels that hold; the action runs once. Holding all four grips/triggers instead opens settings."] = "En Combates terrestres y Combate espacial, elige Terminar turno en la rueda IZQUIERDA. Mantén el stick IZQUIERDO sobre la calavera 1 s, sin otra confirmación. También puedes apuntar con el cráneo DERECHO y mantener su gatillo 1 s, o mantener A 1 s sobre la opción elegida. Cada método funciona por sí solo. Soltar antes cancela esa pulsación; la orden se ejecuta una vez. Mantener los cuatro grips/gatillos abre los ajustes.";
d["Aim with LEFT stick / RIGHT skull + hold RIGHT grip"] = "Apunta con stick IZQUIERDO / cráneo DERECHO + grip DERECHO";
d["Hold RIGHT grip to read; release it to hide."] = "Mantén grip DERECHO para leer; suéltalo para ocultar.";
d["Choose a portrait with the LEFT stick or point with the RIGHT skull, then hold the RIGHT grip to show its original card. This works for allies and enemies in Ground combat and for ships in Space combat. While gripping, the card stays fixed and another pointed portrait replaces it. Release the RIGHT grip, close the wheel or switch its mode to hide it. Inspecting during battle does not select or move the camera."] = "Elige un retrato con el stick IZQUIERDO o apunta con el cráneo DERECHO y mantén el grip DERECHO para mostrar su ficha original. Funciona con aliados y enemigos en Combates terrestres y con naves en Combate espacial. Mientras mantienes el grip, la ficha queda fija y otro retrato señalado la sustituye. Soltar el grip DERECHO, cerrar la rueda o cambiar de modo la oculta. Consultar durante la batalla no selecciona ni mueve la cámara.";
d["RIGHT grip: show card · RIGHT stick: scroll"] = "Grip DERECHO: mostrar ficha · stick DERECHO: scroll";
d["Fixed native cards at the depth of the wheels."] = "Fichas originales fijas, a la profundidad de las ruedas.";
d["Every LEFT-wheel card uses the RIGHT grip: characters, ships, weapons and abilities. Point with the LEFT stick or RIGHT skull, then hold the RIGHT grip. Pointing or clicking alone does not open information. The card remains fixed while held, even if you centre the stick. Centre the RIGHT stick after opening, then move it up/down to scroll long content. Release the RIGHT grip to close."] = "Todas las fichas de la rueda IZQUIERDA usan el grip DERECHO: personajes, naves, armas y habilidades. Apunta con el stick IZQUIERDO o el cráneo DERECHO y mantén el grip DERECHO. Señalar o hacer clic por sí solo no abre la información. La ficha permanece fija mientras lo sostienes, incluso si centras el stick. Centra el stick DERECHO tras abrirla y muévelo arriba/abajo para desplazar el texto largo. Suelta el grip DERECHO para cerrar.";
d["Hold the LEFT grip and trigger. Move the LEFT stick to the inner or outer ring, or point with the RIGHT skull. Hold the RIGHT grip for original information; release it to hide. A or the RIGHT trigger activates an available ability. With a card open, use A or a short trigger click; holding all four buttons for 1 s opens settings. Grey actions cannot run. Release the opening controls to close."] = "Mantén grip y gatillo IZQUIERDOS. Mueve el stick IZQUIERDO al aro interior o exterior, o apunta con el cráneo DERECHO. Mantén grip DERECHO para leer la información original; suéltalo para ocultar. A o el gatillo DERECHO activa una habilidad disponible. Con una ficha abierta usa A o un clic corto del gatillo; mantener los cuatro botones 1 s abre los ajustes. Las acciones grises no se ejecutan. Suelta la combinación de apertura para cerrar.";
d["F1 toggles VR settings with priority over the game. Open this tutorial directly from Help · Touch controls on the main settings page or under Advanced settings. Choose a context and chapter without closing the guide. The welcome is offered once per launch, after the first playable load: YES opens the tutorial and NO continues playing."] = "F1 abre/cierra los ajustes VR con prioridad sobre el juego. Accede al tutorial desde Ayuda · Controles Touch en la página principal de ajustes o en Configuración avanzada. Elige contexto y capítulo sin cerrar la guía. La bienvenida aparece una vez por arranque, tras la primera carga jugable: SÍ abre el tutorial y NO continúa el juego.";
d["Point with the RIGHT skull. One click selects or issues a native order without moving the camera. Double-click the same character, including an enemy, to frame it along its heading at the correct relative height. Ships use their equivalent framing. A also clicks. A deep hold only enters a controllable character or ship; map double-clicks keep their native function."] = "Apunta con el cráneo DERECHO. Un clic selecciona o da la orden original sin mover la cámara. Haz doble clic sobre el mismo personaje, también enemigo, para encuadrarlo según su orientación y altura relativa. Las naves usan su encuadre equivalente. A también hace clic. La pulsación profunda sólo entra en personajes o naves controlables; el doble clic en mapas mantiene su función nativa.";
d["Entry frames our ship on a level board. Click for native orders; double-click frames a ship. Hold the full RIGHT trigger 2 s over our ship for first person. LEFT wheel: actions/ships, with weapons on their native side. RIGHT wheel: menus. Side/bottom panels are hidden; restore them in Advanced settings > Space."] = "La entrada encuadra nuestra nave y nivela el tablero. Clic: orden nativa; doble clic: encuadrar nave. Gatillo DERECHO a fondo 2 s sobre nuestra nave: primera persona. Rueda IZQUIERDA: acciones/naves y armas en su lado original. Rueda DERECHA: menús. Paneles ocultos; restáuralos en Configuración avanzada > Espacio.";
d["Show the original ship panels. Hidden by default: lower, left and right panels are replaced by the wheels. Opened windows and essential popups remain available."] = "Muestra los paneles originales de la nave. Ocultos por defecto: las ruedas sustituyen los paneles inferior, izquierdo y derecho. Las ventanas abiertas y avisos esenciales siguen disponibles.";
d["HOLD LEFT STICK / A / RIGHT TRIGGER 1s · END TURN"] = "MANTÉN STICK IZQ. / A / GATILLO DER. 1s · FIN DE TURNO";
d["HOLD RIGHT GRIP · INFORMATION"] = "MANTÉN GRIP DERECHO · INFORMACIÓN";
d["F1 / four controls 1 s · settings"] = "F1 / cuatro controles 1 s · ajustes";
d["Minimal · combat (saved: {0})"] = "Mínimo · combate (guardado: {0})";
d["Already Minimal"] = "Ya está en Mínimo";
d["View"] = "Ver";
}
} }
