using System.Collections.Generic;
namespace RTMaquetaXR { internal static partial class ModLocalization {
    static partial void AddRelease56(Dictionary<string,string> d) {
        Add(d,"Ground: 3 s in combat / 2 s in exploration","Suelo: 3 s en combate / 2 s en exploración");
        Add(d,"Full right trigger 3 s on ground · move + head view","Gatillo derecho a fondo 3 s al suelo · mover en primera persona");
        Add(d,"R · 3s","D · 3 s");
        Add(d,"HOLD opposite TRIGGER 2s · END TURN","GATILLO contrario 2 s · TERMINAR TURNO");
        Add(d,"Hold the right trigger at least 95% down over a valid destination: three seconds in Ground combat, two seconds in exploration. Once the original game accepts the move, enter the selected actor head view and remain there during movement. No extra move or action-point cost is added. Invalid paths, ability targeting, enemy turns and deployment cannot enter head view. A short click moves normally. B cancels the current action; B or zooming out leaves head view.","Mantén el gatillo derecho al menos al 95 % sobre un destino válido: tres segundos en Combates terrestres y dos en Exploración a pie. Cuando el juego acepte el movimiento, entrarás en primera persona del personaje seleccionado durante el desplazamiento. No se añade otra orden ni coste de puntos de acción. Rutas inválidas, apuntado de habilidades, turnos enemigos y preparación no activan esta vista. Un clic breve mueve normalmente. B cancela; B o alejar la maqueta sale de primera persona.");
        Add(d,"B always cancels the current interaction: settings, wheel, native window or the game pending order. In gameplay it also leaves first-person view. The left menu button is Back/Cancel. Left trigger performs a secondary click. On the End turn wheel option, hold the opposite trigger for two seconds. No extra confirmation window appears. Pointing, A or a short click never ends the turn.","B cancela la interacción actual: opciones, rueda, ventana nativa u orden pendiente. También sale de primera persona. El botón de menú izquierdo vuelve o cancela. El gatillo izquierdo hace clic secundario. Sobre Terminar turno en la rueda, mantén el gatillo contrario dos segundos, sin otra ventana de confirmación. Apuntar, pulsar A o un clic breve no terminan el turno.");
        Add(d,"The same table gestures and LEFT-stick rotation/tilt apply, with ship-relative zoom. Battle entry frames our ship. Click orders without moving the camera; double-click frames the ship along its heading; full RIGHT trigger held for 2 s enters its view. LEFT wheel contains weapons, variants and ship-post abilities; click LEFT stick for the battle ships. RIGHT wheel contains native menus. A or the opposite trigger confirms abilities. On End turn, hold the opposite trigger for two seconds instead; no extra confirmation window appears. Native rules, resources and cooldowns remain authoritative.","Se mantienen los gestos de maqueta y giro e inclinación con el stick IZQUIERDO, con zoom relativo a la nave. Al entrar se encuadra nuestra nave. Un clic da órdenes sin mover cámara; doble clic encuadra según su orientación; gatillo DERECHO a fondo 2 s entra en su vista. Rueda IZQUIERDA: armas, variantes y habilidades de puestos; clic del stick IZQUIERDO alterna las naves. Rueda DERECHA: menús nativos. A o gatillo contrario confirman habilidades. Para Terminar turno, mantén el gatillo contrario dos segundos, sin otra confirmación. Se respetan las reglas, recursos y recargas nativas.");
    }
}}
