using System.Collections.Generic;
namespace RTMaquetaXR
{
    internal static partial class ModLocalization
    {
        static partial void AddCore(Dictionary<string,string> strings)
        {
            Add(strings, "PREPARING VR", "PREPARANDO VR");
            Add(strings, "Connect your headset through Virtual Desktop. The main menu unlocks automatically when VR is ready.", "Conecta el visor mediante Virtual Desktop. El menú principal se desbloqueará automáticamente cuando VR esté preparado.");
            Add(strings, "RETRY VR", "REINTENTAR VR");
            Add(strings, "CONTINUE WITHOUT VR", "CONTINUAR SIN VR");
            Add(strings, "Tabletop VR · OpenXR / VDXR · experimental ", "Maqueta VR · OpenXR / VDXR · experimental ");
            Add(strings, "Stop VR", "Detener VR");
            Add(strings, "Start VR", "Iniciar VR");
            Add(strings, "Hold both grips and triggers for 2 s to open/close settings; right stick navigates/adjusts, A enters, B goes back.", "Ambos gatillos y ambos grips durante 2 s abren/cierran el overlay; stick derecho navega/ajusta, A entra y B vuelve.");
            Add(strings, "Recenter position and orientation", "Recentrar posición y orientación");
            Add(strings, "Toggle flat screen", "Alternar pantalla plana");
            Add(strings, "Bounded Touch camera · scale ", "Cámara Touch cerrada · escala ");
            Add(strings, " · fixed limits 6–14", " · límites fijos 6–14");
            Add(strings, "Navigation panels · use their own placement settings", "Paneles de navegación · usa sus ajustes de posición");
            Add(strings, "Space table · scale ", "Mesa espacial · escala ");
            Add(strings, " · ship-relative limits", " · límites relativos a la nave");
            Add(strings, "Touch movement speed", "Velocidad de desplazamiento Touch");
            Add(strings, "Touch rotation speed", "Velocidad de giro Touch");
            Add(strings, "Touch zoom speed", "Velocidad de zoom Touch");
            Add(strings, "Servo-skull gesture help · upper right", "Ayuda de servocráneos · arriba a la derecha");
            Add(strings, "3D servo-skulls", "Servocráneos 3D");
            Add(strings, "Panel distance", "Distancia del panel");
            Add(strings, "Per-eye resolution", "Resolución por ojo");
            Add(strings, "Resolution 1.00 = full VDXR recommendation. Live change; ", "Resolución 1,00 = recomendación completa de VDXR. Cambio en caliente; ");
            Add(strings, "Per eye: ", "Por ojo: ");
            Add(strings, "; VDXR recommends ", "; VDXR recomienda ");
            Add(strings, "A larger tabletop scale makes the world smaller.", "Una escala de maqueta mayor hace el mundo más pequeño.");
            Add(strings, "TAA sharpness", "Nitidez del TAA");
            Add(strings, "Apply the game FSR setting to VR too", "Aplicar también a VR el FSR configurado en el juego");
            Add(strings, "Skip the third world view; show one eye on the monitor", "Ahorrar la tercera vista del mundo; mostrar un ojo en el monitor");
            Add(strings, "Cull objects outside the headset view", "Ahorrar objetos fuera de la imagen visible del visor");
            Add(strings, "Cull instances outside the headset view", "Ahorrar instancias fuera de la imagen visible del visor");
            Add(strings, "Record render details (diagnostics)", "Registrar detalle del renderizado (diagnóstico)");
            Add(strings, "Update effect visibility for both eyes without drawing another view", "Actualizar visibilidad de efectos para ambos ojos sin dibujar otra vista");
            Add(strings, "Diagnostic recording · this session", "Recogida de diagnóstico · esta sesión");
            Add(strings, "Start automatically when the headset connects through Virtual Desktop", "Iniciar automáticamente al conectar el visor por Virtual Desktop");
            Add(strings, "Flip eye images vertically (Ctrl+Alt+Y)", "Invertir verticalmente las vistas (Ctrl+Alt+Y)");
            Add(strings, "Flip the flat screen vertically", "Invertir verticalmente la pantalla plana");
            Add(strings, "Logs: openxr-native.log, diagnostico-openxr.json and Unity Mod Manager log.", "Registros: openxr-native.log, diagnostico-openxr.json y log de Unity Mod Manager.");
            Add(strings, "Antialiasing · live changes", "Antialiasing · cambio en caliente");
            Add(strings, "Ctrl+Alt+A cycles TAA → SMAA → No AA. No VR restart required.", "Ctrl+Alt+A alterna TAA → SMAA → Sin AA. No requiere reiniciar VR.");
            Add(strings, "The change applies when gameplay resumes.", "El cambio se aplicará al volver a la partida.");
            Add(strings, "NVIDIA · DLSS / DLAA · recommended runtime ", "NVIDIA · DLSS / DLAA · versión recomendada ");
            Add(strings, "DLSS internal resolution", "Resolución interna DLSS");
            Add(strings, "Preset Auto", "Perfil Auto");
            Add(strings, "Preset K", "Perfil K");
            Add(strings, "NVIDIA sharpness", "Nitidez NVIDIA");
            Add(strings, "DLAA uses native resolution; DLSS reconstructs output from a lower internal resolution. Diagnostic only evaluates NVIDIA.", "DLAA usa resolución nativa; DLSS reduce la resolución interna y reconstruye la salida. Diagnóstico sólo evalúa NVIDIA.");
            Add(strings, "FSR is suspended in VR while NVIDIA is active. TAA remains available as a fallback.", "FSR queda suspendido en VR mientras se usa NVIDIA. Esta fase aún conserva el cálculo TAA de reserva.");
            Add(strings, "The selection applies to both eyes when gameplay resumes.", "La selección se aplicará a ambos ojos al volver a la partida.");
            Add(strings, "VR draw distance · live changes", "Distancia de dibujo VR · cambio en caliente");
            Add(strings, "Custom distance", "Distancia personalizada");
            Add(strings, "Move the slider to apply a custom distance. Saved for both eyes without restarting VR.", "Mueve el deslizador para aplicar Personalizada. Se guarda y cambia ambos ojos sin reiniciar VR.");
            Add(strings, "waiting for VR", "pendiente de entrar en VR");
            Add(strings, "Applied: ", "Aplicada: ");
            Add(strings, " · effective limit ", " · límite efectivo ");
            Add(strings, " units", " unidades");
            Add(strings, "Recent FPS: ", "FPS recientes: ");
            Add(strings, "Recent FPS: waiting for a stable sample.", "FPS recientes: esperando una muestra estable.");
            Add(strings, "Resolution and antialiasing remain unchanged. Short distances can clip the background.", "Mantiene la resolución y el antialiasing. Las distancias cortas pueden recortar el fondo.");
            Add(strings, " · stabilizing image", " · estabilizando imagen");
            Add(strings, "Trial ", "Prueba ");
            Add(strings, " · remaining ", " · quedan ");
            Add(strings, " useful s", " s útiles");
            Add(strings, "Keep the same view during comparison.", "Mantén la misma vista durante la comparación.");
            Add(strings, "Cancel trial and restore ", "Cancelar prueba y recuperar ");
            Add(strings, "Trial armed. Close this panel and return to gameplay.", "Prueba preparada. Cierra este panel y vuelve a la partida.");
            Add(strings, "Starts after 5 seconds of stable VR with this panel closed.", "Comenzará tras 5 segundos de VR estable, con el panel cerrado.");
            Add(strings, "Cancel pending trial", "Cancelar prueba pendiente");
            Add(strings, "Prepare automatic comparison", "Preparar comparación automática");
            Add(strings, "Original → 100 → 60 → Original: four phases of 15 useful seconds. Restores your selection at the end.", "Original → 100 → 60 → Original: cuatro fases de 15 s útiles. Al acabar vuelve a tu selección.");
            Add(strings, "Open this panel to cancel a running comparison.", "Abre este panel para cancelar una comparación en curso.");
            Add(strings, "Enable VR to prepare the comparison.", "Activa VR para preparar la comparación.");
            Add(strings, "No AA", "Sin AA");
            Add(strings, "NVIDIA diagnostic", "Diagnóstico NVIDIA");
            Add(strings, "Off", "Desactivado");
            Add(strings, "100 units", "100 unidades");
            Add(strings, "60 units", "60 unidades");
            Add(strings, "Custom", "Personalizada");
            Add(strings, "Original", "Original");
            Add(strings, "Manual", "Manual");
            Add(strings, "Manual during transition/test", "Manual durante transición/prueba");
            Add(strings, "Manual · open horizon", "Manual · horizonte abierto");
            Add(strings, "Adaptive · downward view", "Adaptativa · vista hacia abajo");
            Add(strings, "Adaptive · manual ceiling", "Adaptativa · límite manual");
            Add(strings, "Manual · ground unavailable", "Manual · suelo no disponible");
            Add(strings, "Manual · multiple levels", "Manual · varios niveles");
            Add(strings, "Manual · sample overflow", "Manual · exceso de muestras");
            Add(strings, "Manual · uncertain ground", "Manual · suelo incierto");
            Add(strings, "Version unknown", "Versión desconocida");
            Add(strings, "Source unavailable", "Origen no disponible");
            Add(strings, "Source unidentified", "Origen sin identificar");
            Add(strings, "Mod NVIDIA folder", "Carpeta NVIDIA del mod");
            Add(strings, "External runtime", "Runtime externo");
            Add(strings, "NVIDIA override", "Override de NVIDIA");
            Add(strings, "Recommended version", "Versión recomendada");
            Add(strings, "NOTICE: unverified · permitted", "AVISO: sin verificar · permitido");
            Add(strings, "NOTICE: other version · permitted", "AVISO: otra versión · permitida");
            Add(strings, "Runtime unidentified · permitted", "Runtime sin identificar · permitido");
            Add(strings, "Other NVIDIA runtime · permitted", "Otro runtime NVIDIA · permitido");
            Add(strings, "No effective runtime loaded\nRecommended: {0}", "Ningún runtime activo\nRecomendado: {0}");
            Add(strings, "TAA fallback: {0}", "Respaldo TAA: {0}");
            Add(strings, "Off (releasing resources)", "Desactivado (liberando recursos)");
            Add(strings, "TAA (waiting to switch to {0})", "TAA (esperando cambiar a {0})");
            Add(strings, "{0}: warmup {1}/{2} (TAA visible)", "{0}: preparación {1}/{2} (TAA visible)");
            Add(strings, "DLAA diagnostic (TAA displayed)", "Diagnóstico DLAA (se muestra TAA)");
            Add(strings, "{0}: waiting for confirmed presentation", "{0}: esperando confirmación de imagen");
            Add(strings, "unidentified", "sin identificar");
            Add(strings, "{0} active {1}x{2} -> {3}x{4} | {5} -> {6}", "{0} activo {1}x{2} -> {3}x{4} | {5} -> {6}");
            Add(strings, "Waiting for the headset through Virtual Desktop", "Esperando al visor con Virtual Desktop");
            Add(strings, "Headset unavailable; retrying automatically", "Visor no disponible; reintento automático");
            Add(strings, "OpenXR / VDXR: session created", "OpenXR / VDXR: sesión creada");
            Add(strings, "VR stopped", "VR detenida");
            Add(strings, "Resolution requested; waiting for the stereo pair", "Resolución solicitada; esperando al par estéreo");
            Add(strings, "Output applied: {0} × {1}", "Salida aplicada: {0} × {1}");
            Add(strings, "Output changed; restoring cameras: {0}", "Salida cambiada; restaurando cámaras: {0}");
            Add(strings, "Previous resolution retained: {0}", "Se conserva la resolución anterior: {0}");
            Add(strings, "HUD presets", "Preajustes del HUD");
            Add(strings, "Restore the default HUD or save three custom interface layouts. Eye resolution, DLSS, camera and controls stay unchanged.", "Restaura el HUD predeterminado o guarda tres diseños de interfaz. No cambia la resolución por ojo, DLSS, cámara ni controles.");
            Add(strings, "Restore defaults", "Restaurar valores");
            Add(strings, "Restore the approved HUD and management layout, including panel size, distance, proportions, position, interface resolution and markers. Other mod settings remain unchanged.", "Restaura el diseño aprobado de HUD y Pantallas de gestión: tamaño, distancia, proporción, posición, resolución de interfaz y marcadores. Conserva los demás ajustes del mod.");
            Add(strings, "Default HUD layout", "Diseño del HUD predeterminado");
            Add(strings, "restore", "restaurar");
            Add(strings, "HUD preset {0}", "Preajuste HUD {0}");
            Add(strings, "Save or load the interface settings in this slot.", "Guarda o carga la interfaz en este espacio.");
            Add(strings, "Load", "Cargar");
            Add(strings, "Load the saved HUD position, size, aspect ratio, resolution and visibility. Other mod settings are preserved.", "Carga posición, tamaño, proporción, resolución y visibilidad del HUD. Conserva el resto de ajustes del mod.");
            Add(strings, "Saved", "Guardado");
            Add(strings, "Empty", "Vacío");
            Add(strings, "load", "cargar");
            Add(strings, "Save current layout", "Guardar diseño actual");
            Add(strings, "Save the current HUD in this slot. Replaces the existing preset if the slot is occupied.", "Guarda el HUD actual en este espacio. Sustituye el preajuste existente si está ocupado.");
            Add(strings, "Replace preset {0}", "Sustituir preajuste {0}");
            Add(strings, "Save preset {0}", "Guardar preajuste {0}");
            Add(strings, "save", "guardar");
            Add(strings, "HUD saved to preset {0}", "HUD guardado en preajuste {0}");
            Add(strings, "Default HUD restored", "HUD predeterminado restaurado");
            Add(strings, "HUD preset {0} applied", "Preajuste HUD {0} aplicado");
            Add(strings, "Output applied", "Salida aplicada");
            Add(strings, "Output changed; restoring cameras", "Salida cambiada; restaurando cámaras");
            Add(strings, "Previous resolution retained", "Se conserva la resolución anterior");
            Add(strings, "Could not finish releasing resources", "No se pudo completar la retirada de recursos");
            Add(strings, "VDXR rejected this resolution", "VDXR rechazó esta resolución");
            Add(strings, "{0} units (custom)", "{0} unidades (personalizada)");
            Add(strings, "Manual · too many contacts", "Manual · demasiados contactos");
            Add(strings, "Manual · insufficient ground", "Manual · suelo insuficiente");
            Add(strings, "Could not apply setting", "No se pudo aplicar el ajuste");
            Add(strings, "Native rejected temporal job", "El módulo nativo rechazó el trabajo temporal");
            Add(strings, "temporal-event", "evento temporal");
            Add(strings, "DLSS output size is not set", "No se ha definido la resolución de salida DLSS");
            Add(strings, "Neural hooks are not installed", "Los enlaces de NVIDIA no están instalados");
            Add(strings, "Neural path requires D3D11", "La ruta NVIDIA requiere D3D11");
            Add(strings, "Neural event callback is null", "Falta la función del evento NVIDIA");
            Add(strings, "Waaagh metadata missing", "Faltan metadatos de Waaagh");
            Add(strings, "TAA graph registration IL changed", "Ha cambiado el registro del grafo TAA");
            Add(strings, "TAA registration site absent", "No se encuentra el registro TAA");
            Add(strings, "RTHandleSystem recreation IL changed", "Ha cambiado la recreación de RTHandleSystem");
            Add(strings, "Neural camera ownership mismatch", "La cámara NVIDIA no coincide con su propietario");
            Add(strings, "D3D11 temporal projection flip contract changed", "Ha cambiado la inversión de proyección temporal D3D11");
            Add(strings, "Invalid temporal dimensions/jitter matrix", "Dimensiones o matriz de desplazamiento temporal no válidas");
            Add(strings, "Temporal owner expired", "Ha caducado el propietario temporal");
            Add(strings, "Neural pending queue exceeded bound", "La cola NVIDIA ha superado su límite");
            Add(strings, "Jitter outside installed Halton range", "Desplazamiento fuera del rango Halton instalado");
            Add(strings, "Native returned an invalid event ticket", "El módulo nativo devolvió un identificador de evento no válido");
            Add(strings, "Neural input/output resource alias", "Las entradas y salidas NVIDIA comparten un recurso");
            Add(strings, "Neural color/motion format mismatch", "Los formatos de color y movimiento NVIDIA no coinciden");
            Add(strings, "Texture native pointer unavailable", "El puntero nativo de la textura no está disponible");
            Add(strings, "Per-eye HDR/depth convention changed inside a neural generation", "Ha cambiado la convención HDR/profundidad por ojo durante una generación NVIDIA");
            Add(strings, "Native configuration rejected", "Configuración nativa rechazada");
            Add(strings, "Native backend status unavailable", "Estado del módulo nativo no disponible");
            Add(strings, "Neural job status expired before consumption", "El estado del trabajo NVIDIA caducó antes de utilizarse");
            Add(strings, "Unpaired neural presentation exceeded bound", "La presentación NVIDIA sin par ha superado su límite");
            Add(strings, "Preparing window", "Preparando ventana");
            Add(strings, "Waiting for menu or gameplay to start VDXR", "Esperando al menú o a la partida para iniciar VDXR");
            Add(strings, "native reason", "motivo nativo");
            Add(strings, "bridge ABI mismatch", "ABI del puente incompatible");
            Add(strings, "invalid configuration", "configuración no válida");
            Add(strings, "duplicate eye/frame", "ojo/fotograma duplicado");
            Add(strings, "native job queue full", "cola de trabajos nativos llena");
            Add(strings, "incompatible graphics resource", "recurso gráfico incompatible");
            Add(strings, "unsupported GPU/runtime capability", "función no compatible con la GPU o el runtime");
            Add(strings, "NVIDIA runtime loading or compatibility failure", "error de carga o compatibilidad del runtime NVIDIA");
            Add(strings, "NVIDIA initialization failed", "falló la inicialización NVIDIA");
            Add(strings, "NVIDIA feature creation failed", "falló la creación de la función NVIDIA");
            Add(strings, "NVIDIA evaluation failed", "falló la evaluación NVIDIA");
            Add(strings, "graphics device removed", "dispositivo gráfico desconectado");
            Add(strings, "job cancelled", "trabajo cancelado");
            Add(strings, "stale frame or configuration", "fotograma o configuración caducados");
        }
    }
}

