using System.Collections.Generic;
namespace RTMaquetaXR
{
    internal static partial class ModLocalization
    {
        static partial void AddRelease48(Dictionary<string,string> strings)
        {
            Add(strings, "Select and frame", "Seleccionar y encuadrar");
            Add(strings, "Right trigger: click / double-click", "Gatillo derecho: clic / doble clic");
            Add(strings, "Click selects. Double-click frames the actor or ship.", "Clic: seleccionar. Doble clic: encuadrar personaje o nave.");
            Add(strings, "A normal click never moves the camera. Double-click the same character or ship within 0.35 seconds to frame it at a moderate distance, facing its heading and relative to its actual height. A also clicks. On navigation maps, double-click retains its original function. UI clicks never reposition the camera.", "Un clic normal no mueve la cámara. Haz doble clic sobre el mismo personaje o nave en 0,35 segundos para encuadrarlo a distancia moderada, según su orientación y altura real. A también hace clic. En los mapas de navegación, el doble clic conserva su función original. Los clics en la interfaz no recolocan la cámara.");
            Add(strings, "First-person view", "Vista en primera persona");
            Add(strings, "Right trigger fully held: 2 s", "Gatillo derecho a fondo: 2 s");
            Add(strings, "Hold on a character or ship. B / zoom out leaves.", "Mantén sobre personaje o nave. B / alejar sale.");
            Add(strings, "Point at a character or ship and hold the right trigger at least 95% down for two seconds, without a grip. This enters its head view; the model is hidden from the VR eyes and heading changes are smoothed. Your physical head remains free. B or bringing both gripped hands together returns to the table. Deep holds never enter first person through a menu or navigation map.", "Señala un personaje o nave y mantén el gatillo derecho al menos al 95% durante dos segundos, sin grip. Entras en su vista en primera persona: el modelo se oculta para el visor y sus giros se suavizan. Tu cabeza sigue moviéndose libremente. B o juntar ambas manos con los grips pulsados devuelve la vista a la maqueta. Este gesto no entra en primera persona a través de menús ni mapas de navegación.");
            Add(strings, "Move in first person", "Mover en primera persona");
            Add(strings, "Right trigger fully held on ground: 2 s", "Gatillo derecho a fondo sobre suelo: 2 s");
            Add(strings, "Optional; on by default in exploration and ground combat.", "Opcional; activo por defecto en exploración y combate terrestre.");
            Add(strings, "Hold the right trigger at least 95% down for two seconds over a valid destination. Once the original game accepts the move, enter the selected actor head view and remain there during movement. No extra move or action-point cost is added. Invalid paths, ability targeting, enemy turns and deployment cannot enter head view. A short click moves normally. B cancels the current action; B or zooming out leaves head view.", "Mantén el gatillo derecho al menos al 95% durante dos segundos sobre un destino válido. Cuando el juego acepta el movimiento, entras en la vista del personaje seleccionado y permaneces en ella al moverte. No se añade otra orden ni coste de puntos. Rutas inválidas, apuntado de habilidades, turnos enemigos y despliegue no activan esta vista. Un clic breve mueve normalmente. B cancela la acción; B o alejar el zoom sale de primera persona.");
            Add(strings, "Exploration: move group. Maps: pan.", "Exploración: mover grupo. Mapas: desplazar.");
            Add(strings, "Move the selected group in On-foot exploration. Follow moving characters smoothly follows travel and aligns direction; off keeps the table still. Centre the stick to adopt the new heading. HUD hover does not stop movement; clicks and open menus do. On navigation maps, the right stick pans and left up/down zooms. Space combat keeps native pointer orders instead of stick piloting.", "Mueve el grupo seleccionado en Exploración a pie. Seguir personajes acompaña el movimiento y alinea la dirección con suavidad; desactivado mantiene la maqueta quieta. Centra el stick para adoptar la nueva dirección. Pasar por el HUD no detiene el movimiento; los clics y menús abiertos sí. En los mapas, el stick derecho desplaza y el izquierdo arriba/abajo acerca o aleja. Combate espacial conserva las órdenes con puntero.");
            Add(strings, "Rotate both servo-skulls or change their separation while holding both grips. Exploration zoom is limited by default; the main settings page can unlock it after a performance warning. Space combat has a much wider ship-relative zoom range, independent of the surface. Bringing hands together also leaves character or ship head view. Navigation maps use right-stick pan and left-stick zoom. Management panels use their own size settings.", "Gira ambos servocráneos o cambia su separación manteniendo los grips. El zoom de exploración está limitado por defecto; puedes liberarlo desde el menú principal tras un aviso de rendimiento. Combate espacial tiene un rango mucho más amplio, relativo a la nave e independiente del terrestre. Juntar las manos también sale de primera persona. Los mapas usan desplazamiento con stick derecho y zoom con izquierdo. Las pantallas de gestión tienen sus propios ajustes de tamaño.");
            Add(strings, "Live actions, weapon sets and attack variants.", "Acciones actuales, armas y variantes de ataque.");
            Add(strings, "Hold left grip and trigger. On the surface, left stick click switches Actions / Characters. Actions come from current equipment and skills. Switch weapon chooses a real equipment set; attacks with variants open another wheel of their native subtypes. Centre the stick before choosing from a changed wheel. Preview with the stick or right pointer; A or RIGHT trigger confirms. Space uses active ship weapons. B or releasing the opening controls cancels.", "Mantén grip y gatillo izquierdos. En tierra, clic del stick izquierdo alterna Acciones / Personajes. Las acciones proceden del equipo y habilidades actuales. Cambiar arma elige un conjunto real; los ataques con variantes abren otra rueda con sus subtipos originales. Centra el stick antes de elegir en una rueda que cambie. Stick o puntero derecho muestra la ficha; A o gatillo DERECHO confirma. En espacio aparecen armas de la nave activa. B o soltar la combinación cancela.");
            Add(strings, "Cancel / back", "Cancelar / volver");
            Add(strings, "B cancels the current order, wheel or window.", "B cancela la orden, rueda o ventana actual.");
            Add(strings, "B always cancels the current interaction: settings, wheel, native window or the game pending order. In gameplay it also leaves first-person view. The left menu button is Back/Cancel. Left trigger performs a secondary click. End turn always asks for a separate confirmation; pointing at or previewing an ability never ends the turn.", "B cancela la interacción actual: ajustes, rueda, ventana original u orden pendiente del juego. Durante la partida también sale de primera persona. El botón de menú izquierdo hace Volver/Cancelar. El gatillo izquierdo realiza clic secundario. Terminar turno siempre pide una confirmación aparte; señalar o consultar una habilidad nunca termina el turno.");
            Add(strings, "Right stick: pan · left stick up/down: zoom", "Stick derecho: desplazar · izquierdo arriba/abajo: zoom");
            Add(strings, "Independent size, position, content zoom and presets.", "Tamaño, posición, zoom del contenido y preajustes independientes.");
            Add(strings, "Galactic map and Star system map use their original routes, objects and travel confirmations. Centre both sticks after opening, then right stick pans and left up/down zooms. Point and click to select or travel; B returns. Under Advanced settings > Space, each map has its own size, distance, proportions, position, content zoom and saved layout. There is no group movement, selection rectangle or first-person view in navigation maps.", "Mapa estelar y Mapa galáctico usan sus rutas, objetos y confirmaciones de viaje originales. Centra ambos sticks al abrir: el derecho desplaza y el izquierdo arriba/abajo controla el zoom. Señala y pulsa para seleccionar o viajar; B vuelve. En Configuración avanzada > Espacio, cada mapa tiene tamaño, distancia, proporciones, posición, zoom del contenido y preajuste propios. No hay movimiento del grupo, selección rectangular ni primera persona en estos mapas.");
            Add(strings, "Click orders. Double-click frames. Deep hold: first person.", "Clic: orden. Doble clic: encuadrar. A fondo: primera persona.");
            Add(strings, "Use the same grip gestures and left-stick rotation/tilt, with a wider zoom range. Double-click a ship to frame its heading; hold the right trigger fully for two seconds to enter its view. Left wheel: weapons and their variants; right: ship-post abilities. Preview and confirm with A or the opposite trigger. Native units, resources and cooldowns govern availability. End turn always asks for confirmation. Original panels are visible by default, with an option to hide them.", "Usa los mismos gestos con grips y giro/inclinación con stick izquierdo, con un zoom más amplio. Doble clic sobre nave encuadra su orientación; gatillo derecho a fondo dos segundos entra en su vista. Rueda izquierda: armas y variantes; derecha: habilidades de puestos. Consulta y confirma con A o gatillo contrario. Unidades, recursos y recargas originales determinan la disponibilidad. Terminar turno siempre pide confirmación. Los paneles originales aparecen por defecto y pueden ocultarse.");
            Add(strings, "Select", "Seleccionar");
            Add(strings, "Order", "Orden");
            Add(strings, "Move group", "Mover grupo");
            Add(strings, "Rotate / tilt", "Girar / inclinar");
            Add(strings, "Wheels", "Ruedas");
            Add(strings, "Settings · four controls 2 s", "Ajustes · cuatro controles 2 s");
            Add(strings, "Leave first person", "Salir de primera persona");
            Add(strings, "Full hold 2 s · move in first person", "A fondo 2 s · mover en primera persona");
            Add(strings, "Scroll", "Desplazar");
            Add(strings, "Select / travel", "Seleccionar / viajar");
            Add(strings, "Pan / zoom", "Desplazar / zoom");
            Add(strings, "Pan map", "Desplazar mapa");
            Add(strings, "Zoom / rotate map", "Zoom / girar mapa");
            Add(strings, "Close map · L click also", "Cerrar mapa · también clic L");
            Add(strings, "Actor information", "Ficha de personaje");
            Add(strings, "Centre · keep information", "Centro · mantener ficha");
            Add(strings, "Click · switch mode", "Clic · cambiar modo");
            Add(strings, "Release · close", "Soltar · cerrar");
            Add(strings, "Point · ability info", "Señalar · ficha habilidad");
            Add(strings, "Use ability", "Usar habilidad");
            Add(strings, "Hold 1 s / click · select", "Mantener 1 s / clic · seleccionar");
            Add(strings, "Hold 1 s / click · open", "Mantener 1 s / clic · abrir");
            Add(strings, "Click controls", "Pulsar controles");
            Add(strings, "Navigate / adjust", "Navegar / ajustar");
            Add(strings, "Confirm / back", "Confirmar / volver");
            Add(strings, "Weapons / ship posts", "Armas / puestos");
            Add(strings, "Full right trigger 2 s on ground · move + head view", "Gatillo derecho a fondo 2 s sobre suelo · mover + primera persona");
            Add(strings, "Right stick · pan / left stick · zoom", "Stick derecho · desplazar / stick izquierdo · zoom");
            Add(strings, "All personal settings will be lost. Restore Performance and the approved defaults?", "Se perderán todos los ajustes personales. ¿Restablecer Rendimiento y los valores predefinidos aprobados?");
            Add(strings, "Changing advanced settings can misalign the interface or disrupt image quality, controls and performance.", "Modificar los ajustes avanzados puede desajustar la interfaz, la calidad de imagen, los controles y el rendimiento.");
            Add(strings, "Choose a complete render profile. Window placement and controls stay as configured. Custom restores your saved complete configuration. DLSS/DLAA use NVIDIA hardware; other GPUs use TAA.", "Elige un perfil completo de renderizado. Conserva la posición de ventanas y los controles. Personalizado recupera toda tu configuración guardada. DLSS/DLAA usa NVIDIA; las demás GPU usan TAA.");
            Add(strings, "Compare weapons", "Comparar armas");
            Add(strings, "Confirm", "Confirmar");
            Add(strings, "Continue to advanced settings", "Entrar en configuración avanzada");
            Add(strings, "Control hint placement", "Posición de ayudas de controles");
            Add(strings, "Custom configuration saved.", "Configuración personalizada guardada.");
            Add(strings, "Deep-trigger first-person movement", "Movimiento en primera persona con gatillo a fondo");
            Add(strings, "End the current character or ship turn?", "¿Terminar el turno del personaje o nave actual?");
            Add(strings, "End turn?", "¿Terminar turno?");
            Add(strings, "Free zoom can expose much more scenery and reduce performance. Remove the zoom limit?", "El zoom libre puede mostrar mucho más escenario y reducir el rendimiento. ¿Quitar el límite de zoom?");
            Add(strings, "Free zoom warning", "Aviso de zoom libre");
            Add(strings, "HUD preset", "Preajuste del HUD");
            Add(strings, "Hint height", "Altura de las ayudas");
            Add(strings, "Hint horizontal position", "Posición horizontal de ayudas");
            Add(strings, "Hint size", "Tamaño de las ayudas");
            Add(strings, "Hold the right trigger fully for two seconds on a valid destination to move in first person, in exploration or ground combat. Only an accepted native move enters head view. A short click moves normally.", "Mantén el gatillo derecho a fondo dos segundos sobre un destino válido para moverte en primera persona, en exploración o combate terrestre. Solo entra si el juego acepta la orden. Un clic breve mueve normalmente.");
            Add(strings, "In Management screens, point the right skull at a weapon in the inventory or equipment and press Y. The original game information window shows that weapon together with the equipped weapons eligible for comparison. Stats, bonuses and art remain native. Scroll with the right stick; B closes the information. This never equips, sells or discards an item.", "En Pantallas de gestión, señala con el servocráneo derecho un arma del inventario o equipo y pulsa Y. La ventana original muestra esa arma junto a las equipadas que el juego permite comparar. Estadísticas, bonificaciones y arte siguen siendo originales. Stick derecho desplaza; B cierra la ficha. Esto nunca equipa, vende ni descarta objetos.");
            Add(strings, "Limit exploration zoom", "Limitar zoom de exploración");
            Add(strings, "Map content zoom", "Zoom del contenido del mapa");
            Add(strings, "Map preset restored.", "Preajuste del mapa restaurado.");
            Add(strings, "Map preset saved.", "Preajuste del mapa guardado.");
            Add(strings, "Move the control hints down or up in your view.", "Baja o sube las ayudas de controles en tu campo de visión.");
            Add(strings, "Move the control hints left or right.", "Desplaza las ayudas de controles a izquierda o derecha.");
            Add(strings, "On keeps the predefined tabletop zoom range. Turning this off allows free zoom and can increase rendering cost.", "Activado conserva el rango de zoom predefinido. Desactivado permite zoom libre y puede aumentar el coste de renderizado.");
            Add(strings, "Open the original weapon comparisons together.", "Muestra juntas las fichas comparativas originales.");
            Add(strings, "Point at a weapon + Y", "Señalar un arma + Y");
            Add(strings, "Position and scale the transparent control reminders. These settings affect only the mod hints, including combat, and are saved with your configuration.", "Ajusta posición y tamaño de las ayudas transparentes. Solo afecta a los recordatorios del mod, incluidos los de combate, y se guarda con tu configuración.");
            Add(strings, "Quality preset", "Perfil de calidad");
            Add(strings, "Replace the saved layout for this map only.", "Sustituye únicamente el preajuste guardado de este mapa.");
            Add(strings, "Reset settings", "Restablecer ajustes");
            Add(strings, "Restore Performance and the approved default layout. Your personal configuration will be lost. Confirmation is required.", "Restaura Rendimiento y la disposición predefinida aprobada. Se perderá tu configuración personal. Requiere confirmación.");
            Add(strings, "Restore the saved layout for this map only.", "Recupera únicamente el preajuste guardado de este mapa.");
            Add(strings, "Save all current mod settings, including quality, panels, maps and controls. Replaces your previously saved Custom configuration.", "Guarda todos los ajustes actuales del mod: calidad, paneles, mapas y controles. Sustituye la configuración Personalizada guardada anteriormente.");
            Add(strings, "Save current as Custom", "Guardar actual como Personalizada");
            Add(strings, "Save or restore only this map's size, position, proportions, distance and content zoom. The other map and the rest of the interface are preserved.", "Guarda o recupera solo tamaño, posición, proporciones, distancia y zoom del contenido de este mapa. Conserva el otro mapa y el resto de la interfaz.");
            Add(strings, "Save your custom configuration first.", "Primero guarda tu configuración personalizada.");
            Add(strings, "Scale the icons and short labels together.", "Cambia a la vez el tamaño de los iconos y textos breves.");
            Add(strings, "Set the native camera zoom inside this map. Left stick up/down also changes it. This is independent of panel size and of the other map.", "Ajusta el zoom de la cámara original dentro de este mapa. Stick izquierdo arriba/abajo también lo modifica. Es independiente del tamaño del panel y del otro mapa.");
            Add(strings, "Show space combat panels", "Mostrar paneles del combate espacial");
            Add(strings, "Show the original ship panels. Visible by default during testing. Turning this off keeps opened windows and essential popups available; the wheels still operate.", "Muestra los paneles originales de la nave, visibles por defecto durante las pruebas. Al ocultarlos se conservan las ventanas abiertas y avisos esenciales; las ruedas siguen funcionando.");
            Add(strings, "Switch weapon", "Cambiar arma");
            Add(strings, "This map preset", "Preajuste de este mapa");
            Add(strings, "confirm", "confirmar");
            Add(strings, "Ultra performance", "Ultra rendimiento");
            Add(strings, "Maximum quality", "Máxima calidad");
            Add(strings, "Advanced settings warning", "Aviso de configuración avanzada");
            Add(strings, "WEAPON / ABILITY VARIANTS", "VARIANTES DE ARMA / HABILIDAD");
            Add(strings, "Y · compare pointed weapon", "Y · comparar arma señalada");
            Add(strings, "Compare weapon", "Comparar arma");
            Add(strings, "End-turn confirmation is unavailable.", "La confirmación de terminar turno no está disponible.");
        }
    }
}
