namespace RTMaquetaXR
{
    // Canonical input descriptions: both help surfaces use these same records.
    // Every binding change must edit its record and gesture here; never maintain
    // a separate quick-help string table. New records join both guides by default.
    internal static class TouchBindings
    {
        internal const uint PrimaryButton = 1, SecondaryButton = 2, MenuButton = 4;
        internal const uint ThumbrestControl = 512, ThumbrestContact = 16, StickControl = 16;
        internal const float DistanceDeadZone = .25f, DistanceUnitsPerSecond = 40f;
        internal const string OverlayHelp = "[F1] / [LT]+[LG]+[RT]+[RG] · 1 s · Close  |  [R:Y] · Navigate  |  [R:X] · Adjust  |  [RT] / [A] · Confirm  |  [B] · Back";
        internal const string DistanceBinding = "Left thumbrest touch + right stick up/down";
    }
    internal enum TouchGuideGesture
    {
        PointClick, DragSelection, GroupMovement, TableMove, RotateZoom, Tilt,
        SecondaryClick, Pause, OverlayHold, OverlayNavigate, KeyboardF1, DrawDistance, HeadView, RadialRight, RadialLeft, ExplorationShortcuts, RadialInspect, EndTurn, HeadMove, MapNavigation, InterfaceSettings, WeaponComparison, NativePanels
    }
    internal sealed class TouchControlAssignment
    {
        internal readonly string Id, TitleSource, BindingSource, SummarySource, DetailsSource;
        // Keep references stable when language changes while either help is open.
        // The same record supplies both help surfaces in the selected language.
        internal string Title => ModLocalization.Text(TitleSource);
        internal string Binding => ModLocalization.Text(BindingSource);
        internal string Summary => ModLocalization.Text(SummarySource);
        internal string Details => ModLocalization.Text(DetailsSource);
        internal readonly TouchGuideGesture Gesture;
        internal readonly bool Quick;
        internal string Description => Binding + ". " + Summary + " " + Details;
        internal TouchControlAssignment(string id, string title, string binding, string summary, string details, TouchGuideGesture gesture, bool quick = true)
        { Id = id; TitleSource = title; BindingSource = binding; SummarySource = summary; DetailsSource = details; Gesture = gesture; Quick = quick; }
    }
    internal static partial class TouchControlAssignments
    {
        internal static readonly TouchControlAssignment[] All = {
            new TouchControlAssignment("select", "Select and frame", "Right trigger: click / double-click", "One click selects or orders; two clicks frame.", "Point with the RIGHT skull. One click selects or issues a native order without moving the camera. Double-click the same character, including an enemy, to frame it along its heading at the correct relative height. Ships use their equivalent framing. A also clicks. A deep hold only enters a controllable character or ship; map double-clicks keep their native function.", TouchGuideGesture.PointClick),
            new TouchControlAssignment("head-view", "First-person view", "Right trigger fully held: 2 s", "Hold on a character or ship. B / zoom out leaves.", "Point at the character or ship and hold the right trigger at least 95% down for 2 s, without a grip. Its model is hidden from the VR eyes; heading changes are smoothed. Your head stays free. Left stick turns horizontally. B or bringing both gripped hands together returns to the table. Menus and navigation maps do not enter first person.", TouchGuideGesture.HeadView),
            new TouchControlAssignment("combat-ground-head", "Move in first person", "Full right trigger: 3 s in ground combat; 2 s exploring", "Hold over a valid destination until the move is accepted.", "Without a grip, hold the right trigger at least 95% down over a valid ground destination: 3 s in Ground combat or 2 s in On-foot exploration. After the game accepts the move, the selected actor enters head view. It uses the normal move and action points. It cannot bypass invalid paths, enemy turns, ability targeting or deployment. Optional; enabled by default.", TouchGuideGesture.HeadMove, false),
            new TouchControlAssignment("drag-select", "Select a group", "Right trigger: hold and drag", "Release to select; camera stays.", "Start on ground or a controllable character, drag the rectangle around the group and release the right trigger. This is a mouse-style group selection, not a camera command. It applies on foot, not to navigation maps or ships. To frame an actor, double-click it instead. B cancels a pending order.", TouchGuideGesture.DragSelection),
            new TouchControlAssignment("group-move", "Move the group", "Right stick · selected leader", "Movement keeps the selected character's facing.", "In On-foot exploration, forward, backward and sideways movement use the selected native leader's facing when the RIGHT stick leaves centre. That heading remains fixed during the deflection; centre the stick before capturing the character's current facing again. Camera follow and Touch pointing never redirect movement. Combat keeps its native pointer orders.", TouchGuideGesture.GroupMovement),
            new TouchControlAssignment("table-move", "Move the table", "Either grip: hold and move", "Move your hand to reposition the tabletop.", "Hold either grip, move that hand and release when the table is where you want it. The gesture works in On-foot exploration, both combat modes and 3D dialogue scenes. Your physical head stays free. Grips do not drag Management screens or navigation-map panels; those have independent placement settings.", TouchGuideGesture.TableMove),
            new TouchControlAssignment("rotate-zoom", "Rotate and zoom", "Both grips: hold", "Turn to rotate. Apart: closer. Together: farther.", "Hold both grips and rotate the line between the skulls, or change their separation. Gesture rotation is 15% gentler than before; adjust Gesture rotation sensitivity in Advanced settings > Tabletop. That control does not change stick turning or zoom. Bringing the hands together also leaves first person. Release the grips before using the left stick.", TouchGuideGesture.RotateZoom),
            new TouchControlAssignment("tilt", "Rotate / tilt the table", "Left stick", "Left/right: rotate. Up/down: tilt.", "The LEFT stick rotates or tilts the table. In first person, left/right turns your view in both combat modes too. The Space combat board stays level sideways. An open wheel uses its stick to choose sectors instead. Centre the stick after a grip, wheel or menu before controlling the table again.", TouchGuideGesture.Tilt),
            new TouchControlAssignment("radial-right", "Right wheel", "Right grip + trigger: 0.15 s", "Native menus except the star map of warp routes, which keeps its right options bar.", "Hold right grip and trigger. Keep the RIGHT stick on a valid option for 1 s, or point with the LEFT skull and click its trigger. The system map and space combat keep their menu wheel. The star map of warp routes uses the native right options bar instead. Grey options cannot run. Release the opening controls or press B to close. All four grips/triggers together reserve VR settings.", TouchGuideGesture.RadialRight),
            new TouchControlAssignment("radial-left", "Left wheel · actions", "Left grip + trigger: 0.15 s", "Weapons inside; other abilities outside. No pages.", "Hold the LEFT grip and trigger. Move the LEFT stick to the inner or outer ring, or point with the RIGHT skull. Hold the RIGHT grip for original information; release it to hide. A or the RIGHT trigger activates an available ability. With a card open, use A or a short trigger click; holding all four buttons for 1 s opens settings. Grey actions cannot run. Release the opening controls to close.", TouchGuideGesture.RadialLeft),
            new TouchControlAssignment("radial-weapons", "Weapons and their actions", "Left wheel: inner / outer ring", "Active weapon in the centre; dynamic native choices.", "The centre identifies the active weapon or equipment set with its original art. Changing weapon is distinct from attacks, ammunition/effects and reload. Switch weapon appears only when at least two loadouts contain equipped weapons; empty slots are not alternatives. The wheel follows the selected actor, current equipment and available abilities. After a weapon change the wheel refreshes: centre the stick and release confirmation before choosing the next action.", TouchGuideGesture.RadialLeft, false),
            new TouchControlAssignment("radial-left-modes", "Left wheel · participants", "Left stick click: switch mode", "Actions / Characters; Actions / Ships in space.", "Click the LEFT stick to alternate modes. In exploration, actions require exactly one selected character; party selection uses a 1 s stick hold or RIGHT-trigger click and never moves the camera. Ground deployment opens Characters first and a friendly portrait also selects that unit for placement. Active battles open Actions first. Extra participants use another ring.", TouchGuideGesture.RadialInspect, false),
            new TouchControlAssignment("combat-inspect", "Inspect a combatant", "Aim with LEFT stick / RIGHT skull + hold RIGHT grip", "Hold RIGHT grip to read; release it to hide.", "Choose a portrait with the LEFT stick or point with the RIGHT skull, then hold the RIGHT grip to show its original card. This works for allies and enemies in Ground combat and for ships in Space combat. While gripping, the card stays fixed and another pointed portrait replaces it. Release the RIGHT grip, close the wheel or switch its mode to hide it. Inspecting during battle does not select or move the camera.", TouchGuideGesture.RadialInspect, false),
            new TouchControlAssignment("wheel-cards", "Read original information", "RIGHT grip: show card · RIGHT stick: scroll", "Fixed native cards at the depth of the wheels.", "Every LEFT-wheel card uses the RIGHT grip: characters, ships, weapons and abilities. Point with the LEFT stick or RIGHT skull, then hold the RIGHT grip. Pointing or clicking alone does not open information. The card remains fixed while held, even if you centre the stick. Centre the RIGHT stick after opening, then move it up/down to scroll long content. Release the RIGHT grip to close.", TouchGuideGesture.RadialInspect, false),
            new TouchControlAssignment("end-turn", "End the turn", "LEFT stick / A / RIGHT trigger: hold 1 s", "Three independent ways to end the turn.", "In Ground combat and Space combat, choose End turn on the LEFT wheel. Keep the LEFT stick over its skull for 1 s, without any other confirmation. Alternatively, aim with the RIGHT skull and hold its trigger for 1 s, or hold A for 1 s on the selected option. Each method works alone. Releasing early cancels that hold; the action runs once. Holding all four grips/triggers instead opens settings.", TouchGuideGesture.EndTurn, false),
            new TouchControlAssignment("combat-status", "Combat status on the wheel", "Left wheel: native live indicators", "Veil, momentum and the selected ally; ship integrity in space.", "Ground combat keeps the original veil and momentum indicators on the left wheel, plus health, action/movement points and effects for the selected ally. Inspecting an enemy does not replace that ally. Space combat shows our ship integrity. Participant order numbers and the player-turn highlight follow the native battle; unavailable actions remain grey.", TouchGuideGesture.RadialInspect, false),
            new TouchControlAssignment("tactical-info", "Tactical information", "Hold Y during your turn", "Show original combat information only while requested.", "During your Ground combat turn, hold Y to show native information for the pointed unit or affected attack targets, including allies. The attacker is shown only if also affected. The floating cover badge stays hidden. Release Y to hide the information. The game continues running; this control is inactive during enemy turns.", TouchGuideGesture.NativePanels, false),
            new TouchControlAssignment("exploration-shortcuts", "Map / reveal objects", "LEFT stick: map · RIGHT stick 1 s: group · Y: highlight · A: interact", "One available action executes directly; several open a wheel.", "In On-foot exploration, A activates a discovered interaction near the selected group. If several interactions are nearby, choose an available one with the RIGHT stick held for 1 s, or point with the LEFT Touch and hold its trigger for 1 s. Unavailable choices remain grey. B closes the wheel. Hold Y to highlight loot and discovered interaction icons. Doors, chests and other direct world actions keep their RIGHT-trigger interaction.", TouchGuideGesture.ExplorationShortcuts),
            new TouchControlAssignment("secondary", "Cancel / back", "Left trigger / B", "B cancels the current order, wheel or window.", "B cancels the current interaction, closes the active wheel/settings/native window or cancels an order. In gameplay it also leaves first person. The left menu button is Back/Cancel. The left trigger performs the native secondary click; when the right wheel is open it confirms the option pointed at by the left skull instead.", TouchGuideGesture.SecondaryClick),
            new TouchControlAssignment("pause", "Pause", "X button", "Pause or resume the game.", "Press X when gameplay input is available to invoke the original pause action. This does not skip a turn or interrupt a native modal window. B cancels a pending action; use the right-trigger pointer for native menu buttons.", TouchGuideGesture.Pause),
            new TouchControlAssignment("overlay", "VR settings", "Both triggers + grips: 1 s", "Open or close settings. Takes priority over wheels.", "Hold both triggers and both grips together for 1 s to open or close settings. Release all four before repeating. A completed settings chord closes the wheel without executing its action. F1 also toggles settings and takes priority over game bindings.", TouchGuideGesture.OverlayHold),
            new TouchControlAssignment("overlay-navigation", "Use VR settings", "Point + A / right trigger", "A or trigger activates the pointed control. B returns.", "Point at a row or button and release A or the RIGHT trigger over it to activate. Release both before confirming again. The RIGHT stick navigates and changes values; away from the panel, A/trigger uses the focused option. B goes back. F1 toggles settings, F2/F3 change a value and F4 activates the focused action.", TouchGuideGesture.OverlayNavigate),
            new TouchControlAssignment("keyboard-settings", "Keyboard settings shortcut", "F1", "Open or close VR settings and help.", "F1 toggles VR settings with priority over the game. Open this tutorial directly from Help · Touch controls on the main settings page or under Advanced settings. Choose a context and chapter without closing the guide. The welcome is offered once per launch, after the first playable load: YES opens the tutorial and NO continues playing.", TouchGuideGesture.KeyboardF1, false),
            new TouchControlAssignment("context-reminder", "Control reminders", "Short RIGHT stick click", "Hidden at launch. Available in exploration and both combats.", "A short RIGHT stick click shows/hides contextual controls in On-foot exploration, Ground combat and Space combat. Holding it for 1 s in exploration frames the group without toggling help. Release and centre the RIGHT stick before moving again. Hold button Y in exploration to highlight objects. Hints stay hidden on the main menu, maps and dialogue. Adjust placement and size in Advanced settings. The separate gesture indicator is optional and off by default.", TouchGuideGesture.ExplorationShortcuts, false),
            new TouchControlAssignment("navigation-space", "Star and galactic maps", "RIGHT stick: pan · LEFT up/down: zoom", "Star map: warp routes. Galactic map: system planets.", "Centre both sticks after opening the map. RIGHT stick pans; LEFT up/down zooms. Point with the right skull and click or press A for native objects, routes and travel confirmations. B goes back. Warp routes keep the native right options bar; system planets keep the right wheel. These maps have no group movement, selection rectangle or first-person view.", TouchGuideGesture.MapNavigation, false),
            new TouchControlAssignment("map-layout", "Adjust each map panel", "Advanced settings > Space", "Each navigation map saves its own placement and content zoom.", "Star map (warp routes) and Galactic map (planets) have independent width, distance, proportions, position, content zoom and saved layouts in Advanced settings > Space. Changing one map does not resize the other. Panel size changes how large the whole window looks; content zoom changes the map inside it.", TouchGuideGesture.InterfaceSettings, false),
            new TouchControlAssignment("space-battle", "Space combat controls", "Table gestures + native tactical pointer", "Click orders. Double-click frames. Deep hold: first person.", "Entry frames our ship on a level board. Click for native orders; double-click frames a ship. Hold the full RIGHT trigger 2 s over our ship for first person. LEFT wheel: actions/ships, with weapons on their native side. RIGHT wheel: menus. Side/bottom panels are hidden; restore them in Advanced settings > Space.", TouchGuideGesture.RotateZoom, false),
            new TouchControlAssignment("native-panels", "Native windows and dialogue", "Right aim + trigger / A · RIGHT stick: scroll", "Use the original choices, equipment and story-book pages.", "Point with the right skull and click the RIGHT trigger or A. The RIGHT stick scrolls long native content; centre it after opening a new window. B returns or cancels when the game permits. Dialogue choices, tutorial notices and story-book decisions keep their native rules. Settings do not choose a dialogue answer for you.", TouchGuideGesture.NativePanels, false),
            new TouchControlAssignment("dialogue-camera", "Camera during dialogue", "Grips + LEFT stick in 3D scenes", "Automatic close framing; you can adjust the scene view.", "3D dialogue scenes use their own close framing. Reposition with one grip, rotate/zoom with two grips or rotate/tilt with the LEFT stick. Your head remains free. Native text choices still use the right pointer. Returning from ordinary windows restores the earlier table position; it does not frame the group again.", TouchGuideGesture.TableMove, false),
            new TouchControlAssignment("weapon-comparison", "Compare weapons", "Point at a weapon + Y", "Open the original weapon comparisons together.", "In Management screens, point the right skull at an inventory/equipment weapon and press Y. The game shows that weapon alongside equipped weapons eligible for comparison, with its own statistics, bonuses and art. RIGHT stick scrolls; B closes. This never equips, sells or discards an item.", TouchGuideGesture.WeaponComparison, false),
            new TouchControlAssignment("hud-layout", "Fit native windows", "Advanced settings > Interface / Space", "Dialogue, management and navigation maps have separate layouts.", "Adjust size, distance, aspect and position for the relevant screen, then save its HUD preset. Management windows and both navigation maps have their own settings. Wheels keep an independent physical size; information cards keep a fixed view position. Updating the mod preserves your saved custom layout.", TouchGuideGesture.InterfaceSettings, false),
            new TouchControlAssignment("draw-distance", "Draw distance", "Left thumbrest touch + right stick up/down", "Surface only. Optional; off by default.", "Enable Draw distance shortcut in Tabletop settings to use it during On-foot exploration and Ground combat. Rest your left thumb on the capacitive thumbrest, then move the RIGHT stick up to draw farther or down to draw less. No click is needed. Centre the stick after releasing the thumbrest. It is inactive in navigation maps and Space combat.", TouchGuideGesture.DrawDistance),
            new TouchControlAssignment("quality-settings", "Image and saved profiles", "Main settings: image / profiles / SAVE", "Common controls first; full settings under Advanced.", "Choose rendering, output resolution, DLSS scale and engine effects on the main page. Select Virtual Desktop (VDXR) or Meta Quest Link / Air Link through OpenXR runtime; a runtime change requires restarting the game. Controls are shared by both. Custom starts with the reference configuration; SAVE stores your complete current setup and confirms it. Reset asks first and discards personal changes. DLSS/DLAA failure displays the current image without AA; TAA remains a separate manual choice.", TouchGuideGesture.InterfaceSettings, false),
            new TouchControlAssignment("optional-engine", "Optional engine controls", "Advanced settings: restart where indicated", "Experimental choices are optional, with no promised FPS gain.", "Selective engine cadence is off by default. Its 72/36, 90/45 and 120/60 pairs require restart and do not change headset refresh in either OpenXR runtime. The engine-block switches also apply after restart. They do not halve every game system. Keep a configuration you can compare; your head, Touch and stereo views retain their own update paths.", TouchGuideGesture.InterfaceSettings, false),
            new TouchControlAssignment("diagnostics-effects", "Diagnostics and combat effects", "Main settings / Advanced settings", "Optional logging and temporary combat effects.", "The master diagnostics switch stops our managed/native traces and diagnostic collection; it does not silence the game or other mods. Automatic minimum combat effects is off by default. When enabled, ground deployment/combat temporarily uses Minimum and restores your chosen base level afterwards. It never overwrites that saved preference.", TouchGuideGesture.InterfaceSettings, false),
        };
    }
}
